void mx_image_color2(string file, string layer, color2 default_value, vector2 texcoord, string uaddressmode, string vaddressmode, string framerange, int frameoffset, string frameendaction, output color2 out)
{
    vdirection(texcoord, texcoord);
    color missingColor = color(default_value.r, default_value.a, 0.0);
    color rgb = texture(file, texcoord.x, texcoord.y, "subimage", layer, "missingcolor", missingColor, "wrap", uaddressmode);
    out.r = rgb[0];
    out.a = rgb[1];
}
