void mx_remap_color4(color4 in, color4 inlow, color4 inhigh, color4 gamma, color4 outlow, color4 outhigh, int doclamp, output color4 result)
{
    color4 zero = {color(0.0), 0.0};
    color4 one = {color(1.0), 1.0};

    // remap from [inlow, inhigh] to [0,1]
    result = remap(in, inlow, inhigh, zero, one, 0);

    // apply gamma
    result = fgamma(result, gamma);

    // remap from [0,1] to [outlow, outhigh]
    result = remap(result, zero, one, outlow, outhigh, doclamp);
}
