void mx_remap_vector2(vector2 in, vector2 inlow, vector2 inhigh, vector2 gamma, vector2 outlow, vector2 outhigh, int doclamp, output vector2 result)
{
    vector2 zero = {0.0, 0.0};
    vector2 one = {1.0, 1.0};

    // remap from [inlow, inhigh] to [0,1]
    result = remap(in, inlow, inhigh, zero, one, 0);

    // apply gamma
    result = fgamma(result, gamma);

    // remap from [0,1] to [outlow, outhigh]
    result = remap(result, zero, one, outlow, outhigh, doclamp);
}
