void mx_remap_vector3(vector in, vector inlow, vector inhigh, vector gamma, vector outlow, vector outhigh, int doclamp, output vector result)
{
    vector zero = {0.0, 0.0, 0.0};
    vector one = {1.0, 1.0, 1.0};

    // remap from [inlow, inhigh] to [0,1]
    result = remap(in, inlow, inhigh, zero, one, 0);

    // apply gamma
    result = fgamma(result, gamma);

    // remap from [0,1] to [outlow, outhigh]
    result = remap(result, zero, one, outlow, outhigh, doclamp);
}
