void mx_remap_vector4(vector4 in, vector4 inlow, vector4 inhigh, vector4 gamma, vector4 outlow, vector4 outhigh, int doclamp, output vector4 result)
{
    vector4 zero = {0.0, 0.0, 0.0, 0.0};
    vector4 one = {1.0, 1.0, 1.0, 1.0};

    // remap from [inlow, inhigh] to [0,1]
    result = remap(in, inlow, inhigh, zero, one, 0);

    // apply gamma
    result = fgamma(result, gamma);

    // remap from [0,1] to [outlow, outhigh]
    result = remap(result, zero, one, outlow, outhigh, doclamp);
}
