#ifndef MATERIALX_OslValidator_H
#define MATERIALX_OslValidator_H

#include <MaterialXView/ShaderValidators/ShaderValidator.h>
#include <MaterialXView/ShaderValidators/ExceptionShaderValidationError.h>
#include <MaterialXView/Handlers/ImageHandler.h>
#include <vector>
#include <string>
#include <map>

namespace MaterialX
{
// Shared pointer to an OslValidator
using OslValidatorPtr = std::shared_ptr<class OslValidator>;

/// @class @OslValidator
/// Helper class to perform validation of OSL source code generated by an OSL code generator.
///
/// The main services provided are:
///     - Source code validation: Use of oslc to compile and test output results
///     - Introspection check: None at this time.
///     - Binding: None at this time.
///     - Render validation: Use of "testshade" to output rendered images. Assumes source compliation was success
///       as it depends on the existence of corresponding .oso files.
///
class OslValidator : public ShaderValidator
{
  public:
    /// Create an OSL validator instance
    static OslValidatorPtr create();

    /// Destructor
    virtual ~OslValidator();

    /// @name Setup
    /// @{

    /// Internal initialization required for program validation and rendering.
    /// An exception is thrown on failure.
    /// The exception will contain a list of initialization errors.
    void initialize() override;

    /// @}
    /// @name Validation
    /// @{

    /// Validate creation of an OSL program based on an input shader
    ///
    /// A valid executable and include path must be specified before calling this method.
    /// setOslCompilerExecutable(), and setOslIncludePath(). 
    ///
    /// Additionally setOslOutputFilePath() should be set to allow for output of .osl and .oso
    /// files to the appropriate path location to be used as input for render validation.
    /// 
    /// If render validation is not required, then the same temporary name will be used for
    /// all shaders validated using this method.
    /// @param shader Input shader
    void validateCreation(const ShaderPtr shader) override;

    /// Validate creation of an OSL program based upon a shader string for a given
    /// shader "stage". There is only one shader stage for OSL thus
    /// @param stages List of shader strings. Only first string in list is examined.
    void validateCreation(const std::vector<std::string>& stages) override;

    /// Validate inputs for the compiled OSL program. 
    /// Note: Currently no validation has been implemented.
    void validateInputs() override;

    /// Validate that an appropriate rendered result is produced.
    /// This is done by using either "testshade" or "testrender".
    /// Currently only "testshade" is supported.
    ///
    /// Usage of both executables requires compiled source (.oso) files as input.
    /// A shader output must be set before running this test via the setOslOutputName() method to
    /// ensure that the appropriate .oso files can be located.
    ///
    /// @param orthographicView Render orthographically
    void validateRender(bool orthographicView=true) override;

    /// @}
    /// @name Utilities
    /// @{

    /// Save the current contents a rendering to disk.
    /// @param fileName Name of file to save rendered image to.
    void save(const std::string& fileName) override;
    
    /// @}
    /// @name Compilation settings
    /// @{

    /// Set the OSL executable path string. Note that it is assumed that this
    /// references the location of the oslc executable.
    /// @param executable Full path to OSL compiler executable
    void setOslCompilerExecutable(const std::string executable)
    {
        _oslCompilerExecutable = executable;
    }

    /// Set the OSL include path string. 
    /// @param includePathString Include path(s) for the OSL compiler. This should include the
    /// path to stdosl.h    
    void setOslIncludePath(const std::string includePathString)
    {
        _oslIncludePathString = includePathString;
    }

    /// Set OSL output name, excluding any extension.
    /// During compiler checking an OSL file of the given output name will be used if it
    /// is not empty. If temp then OSL will be written to a temporary file.
    /// @param filePathString Full path name
    void setOslOutputFilePath(const std::string filePathString)
    {
        _oslOutputFilePathString = filePathString;
    }

    /// Set the OSL shader output name. 
    /// This is used during render validation if "testshade" is executed.
    /// @param outputName Name of shader output
    void setOslShaderOutputName(const std::string outputName)
    {
        _oslShaderOutputName = outputName;
    }

    /// Set the OSL shading tester path string. Note that it is assumed that this
    /// references the location of the "testshade" executable.
    /// @param executable Full path to OSL "testshade" executable
    void setOslTestShadeExecutable(const std::string executable)
    {
        _oslTestShadeExecutable = executable;
    }

    /// Set the OSL rendering tester path string. Note that it is assumed that this
    /// references the location of the "testrender" executable.
    /// @param executable Full path to OSL "testrender" executable
    void setOslTestRenderExecutable(const std::string executable)
    {
        _oslTestRenderExecutable = executable;
    }

    /// Used to toggle to either use testrender or testshade during render validation
    /// By default testshade is used.
    /// @param useTestRender Indicate whether to use testrender.
    void useTestRender(bool useTestRender)
    {
        _useTestRender = useTestRender;
    }

    /// @}

  protected:
    ///
    /// Compile OSL code stored in a file. Return errors in result string 
    /// @param oslFileName Name of OSL file
    void compileOSL(const std::string& oslFileName);

    ///
    /// Shade using OSO input file. Return errors in result string 
    /// @param shaderName Name of OSL shader. A corresponding .oso file is assumed to exist
    /// @param outputName Name of OSL shader output to use.
    void shadeOSL(const std::string& shaderName, const std::string& outputName);

    /// Constructor
    OslValidator();

  private:
    /// "oslc" executable name
    std::string _oslCompilerExecutable;
    /// OSL include path name
    std::string _oslIncludePathString;
    /// Output file path. File name does not include an extension
    std::string _oslOutputFilePathString;

    /// "testshade" executable name
    std::string _oslTestShadeExecutable;
    /// "testrender" executable name
    std::string _oslTestRenderExecutable;
    /// Name of output on shader. Used for rendering with "testshade"
    std::string _oslShaderOutputName;
    /// Use "testshade" or "testender" for render validation
    bool _useTestRender;
};

} // namespace MaterialX
#endif
