void mx_image_color3(string file, string layer, color default_value, vector2 texcoord, string uaddressmode, string vaddressmode, string framerange, int frameoffset, string frameendaction, output color out)
{
    vdirection(texcoord, texcoord);
    color missingColor = default_value;
    out = texture(file, texcoord.x, texcoord.y, "subimage", layer, "missingcolor", missingColor, "wrap", uaddressmode);
}
