#!/usr/bin/env python
#
# Copyright Contributors to the MaterialX Project
# SPDX-License-Identifier: Apache-2.0
#
'''
Transpile MaterialX genglsl node fragments and genglsl/lib helpers to genwgsl (WGSL).

genglsl sources are not complete shaders: they use `#include`, `$`-tokens, and define functions
with no entry point. This tool wraps each target in a naga-parseable GLSL fragment shader, runs
`naga` (GLSL -> WGSL), then post-processes naga's SSA-style output into readable genwgsl fragments.

Only hand-written `.wgsl` (the files listed in skip_transpile.txt) are committed; every other genwgsl
`.wgsl` is a derived artifact — not committed, regenerated by CI before build and removed from an
in-place tree with `--clean`. Re-running keeps genwgsl in sync with genglsl.

Node transpilation (per mx_*.glsl function):
  - ONE function body per naga call; lib context is *prototypes + #defines + structs*, not full
    lib bodies — keeps parameter names clean and avoids `$`-tokens inside lib implementations.
  - Skipped: image/hextiled texture nodes (combined GLSL sampler2D has no split WGSL
    texture_2d+sampler equivalent) and light shaders (need the dynamic LightData struct).
  - Expected fallback: mx_chiang_hair_bsdf (array `out` params, isinf, and a sampler-bound
    indirect term — see EXPECTED_FALLBACK).

Lib transpilation (`transpileLibs`, runs before nodes):
  - Each genglsl/lib/*.glsl becomes genwgsl/lib/*.wgsl in topological #include order (22 files).
  - Default: per-function transpile with full bodies of #included lib deps inlined, plus
    LIB_PREAMBLE (generator-option pins), texture stubs, and mangle() overload renaming.
  - Sibling-body path for mx_microfacet_specular, mx_microfacet_sheen, mx_flake, mx_noise
    (heavy intra-file call graphs: transitive in-file callees + overload-aware topo sort).
  - Special case: mx_closure_type (static struct preamble + transpiled makeClosureData).
  - Lib transpile failures are hard errors (no hand-port fallback).

Usage:
  python mxgenwgsl.py --libraries libraries --out libraries
  python mxgenwgsl.py --libraries libraries --out build/genwgsl_generated
  python mxgenwgsl.py --libraries libraries --only mx_conductor_bsdf mx_math
  python mxgenwgsl.py --libraries libraries --clean   # delete generated .wgsl, keep skip_transpile.txt
'''

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from mxwgslcleanup import cleanupFunction, fnBase

# The naga CLI (GLSL->WGSL). Resolved in main() via resolveNaga(): --naga arg, then $NAGA, then a
# `naga` on PATH; main() overwrites this global before any transpilation runs.
# Install with `cargo install naga-cli` (see https://github.com/gfx-rs/wgpu/tree/trunk/naga).
NAGA = "naga"


def resolveNaga(explicit=None):
    '''Return a runnable naga command: explicit --naga, else $NAGA, else `naga` from PATH.'''
    return explicit or os.environ.get("NAGA") or shutil.which("naga") or "naga"


def nagaVersion(naga):
    '''Return naga's version string if it runs, else None (used to fail early with guidance).'''
    try:
        r = subprocess.run([naga, "--version"], capture_output=True, text=True)
        return r.stdout.strip() if r.returncode == 0 else None
    except OSError:
        return None


def discoverLibs(libroot):
    '''Library folders to process: every immediate subdirectory of --libraries that has a `genglsl`
    node directory. Today that is stdlib/pbrlib/lights (bxdf is nodegraph-based, nprlib/targets have
    no genglsl node fragments), but auto-discovering means new or downstream libraries are picked up
    without editing this tool. Sorted for stable output ordering.'''
    libroot = Path(libroot)
    if not libroot.is_dir():
        return []
    return sorted(p.name for p in libroot.iterdir() if (p / "genglsl").is_dir())


# Node shaders that can't be transpiled and stay hand-written, matched by file-stem regex. Two
# root causes:
#   * Texture nodes -- the genglsl uses the generator tokens $texSamplerSignature/$texSamplerSampler2D
#     (see mx_image_*.glsl, mx_hextiledimage.glsl), which the GLSL backend substitutes as ONE combined
#     `sampler2D`. WGSL instead needs SEPARATE `texture_2d<f32>` + `sampler` params and textureSample*
#     calls (cf. the hand-written mx_hextiledimage.wgsl). naga's GLSL frontend models the combined
#     sampler and won't split it, so any signature it emits is wrong -- skip rather than mis-emit.
#   * Light shaders -- take the dynamically-generated `LightData` struct the fragment context can't
#     supply, so they can't be assembled into a standalone naga-parseable shader.
SKIP_PATTERNS = [re.compile(p) for p in (
    r"image",      # texture nodes: combined sampler2D has no split texture_2d+sampler equivalent
    r"hextiled",   # texture nodes (same combined-sampler limitation)
    r"_light$",    # light shaders take the dynamically-generated LightData struct
)]

# Nodes that are intentionally NOT generated and remain hand-written, by file stem. They are
# EXPECTED to fail transpile, so they don't constitute a build error -- only an *unexpected* failure
# (a previously-generable node that broke, e.g. after a genglsl change) sets a non-zero exit. Keep
# this in sync with the committed hand-written .wgsl files: if one starts transpiling cleanly, the
# tool warns so it can be removed here.
#
# mx_chiang_hair_bsdf hits three distinct blockers in its genglsl source:
#   1. array-valued `out` params -- mx_hair_alpha_angles(out vec2 angles[4]) and
#      mx_hair_attenuation(out vec3 Ap[4]); naga's GLSL frontend can't lower `out` arrays to a WGSL
#      ptr<function, array<...>> parameter;
#   2. isinf() in mx_hair_azimuthal_scattering -- no WGSL builtin, and naga doesn't synthesize one;
#   3. the indirect branch calls mx_environment_radiance(), a sampler-bound helper kept hand-written,
#      so the post-process arity/unsupported check would reject the node even if 1-2 were solved.
EXPECTED_FALLBACK = {
    "mx_chiang_hair_bsdf",
}

# Hand-written genwgsl .wgsl files that must never be transpiled, listed in skip_transpile.txt
# (next to this script). Covers both whole hand-maintained lib dirs and individual sampler-bound
# helpers naga's GLSL frontend cannot express (environment radiance/prefilter, shadow-map lookups),
# plus the SKIP_PATTERNS node shaders so `--clean` retains them. Entries are repo-relative paths;
# keyed here as libroot-relative POSIX (e.g. stdlib/genwgsl/lib/mx_math.wgsl).
DO_NOT_TRANSPILE_FILE = Path(__file__).with_name("skip_transpile.txt")
_doNotTranspile = None


def loadDoNotTranspile():
    '''Set of hand-written genwgsl .wgsl files (libroot-relative POSIX paths) that must never be
    transpiled or removed by --clean. Parsed once from skip_transpile.txt; a leading
    `libraries/` component is stripped so the keys are anchored at --libraries.'''
    global _doNotTranspile
    if _doNotTranspile is None:
        keep = set()
        for raw in DO_NOT_TRANSPILE_FILE.read_text(encoding="utf-8").splitlines():
            line = raw.split("#", 1)[0].strip().replace("\\", "/").lstrip("/")
            if not line:
                continue
            if line.startswith("libraries/"):
                line = line[len("libraries/"):]
            keep.add(line)
        _doNotTranspile = keep
    return _doNotTranspile


def isHandWrittenLib(lib, stem):
    '''True if genwgsl/lib/<stem>.wgsl for this library is hand-written (in skip_transpile.txt)
    and must be left untouched rather than transpiled from its genglsl source.'''
    return f"{lib}/genwgsl/lib/{stem}.wgsl" in loadDoNotTranspile()

TYPE_FIXUPS = [
    (re.compile(r"\bvec([234])<f32>"), r"vec\1f"),
    (re.compile(r"\bvec([234])<i32>"), r"vec\1i"),
    (re.compile(r"\bvec([234])<u32>"), r"vec\1u"),
    (re.compile(r"\bmat([234])x\1<f32>"), r"mat\1x\1f"),
]

# -----------------------------------------------------------------------------
# overload name mangling
# -----------------------------------------------------------------------------
#
# WGSL has no function overloading, so each GLSL overload needs a distinct genwgsl name. The *keys*
# (name + parameter types) are discovered by scanning genglsl (buildContext's `overloaded` set),
# so they are never hand-listed. Only the *naming* is specified here, and only for the families
# whose hand-written stdlib names don't follow the default first-parameter-type rule:
#
#   * SUFFIX_SCHEME - families with a regular, rule-based suffix (keyed by base name).
#   * EXCEPTIONS    - individual (name, types) whose genwgsl name is semantic/irregular, or a
#                     primary overload that stays unsuffixed. A None value means "intentionally
#                     unsupported" (a node calling it stays hand-written).
#
# mangle() is the single source of truth for both emitting lib definitions (wgslFnName) and
# rewriting node calls (remapCalls). The generated names are validated against the real genwgsl
# lib after generation (buildWgslLibSymbols / checkLibArity), so a wrong rule fails loudly.

def _suffixToken(t):
    '''GLSL type -> the token used in a genwgsl overload suffix (float -> f32, else the GLSL name).'''
    return "f32" if t == "float" else t


def _firstTypeSuffix(types):
    '''`_<type of first param>`, e.g. mx_square(vec3) -> _vec3, mx_bilerp(float,...) -> _f32.'''
    return "_" + _suffixToken(types[0])


def _allTypesSuffix(types):
    '''`_<t0>_<t1>...` for every param, e.g. mx_matrix_mul(vec2,mat2) -> _vec2_mat2.'''
    return "".join("_" + _suffixToken(t) for t in types)


def _vecDimSuffix(types):
    '''`_2d`/`_3d` from the first vector param's dimension (mx_perlin_noise_float(vec3) -> _3d).'''
    for t in types:
        m = re.match(r"u?vec([234])$", t)
        if m:
            return "_" + m.group(1) + "d"
    raise ValueError(f"vec_dim scheme: no vector parameter in {types}")


def _gradientDimSuffix(types):
    '''`_2d`/`_3d` from coordinate count (hash + N coords): 3 params -> _2d, 4 params -> _3d.'''
    return "_" + str(len(types) - 1) + "d"


def _cellposDimSuffix(types):
    '''`_2d`/`_3d` from cell-position arg count: 5 params -> _2d, 7 params -> _3d.'''
    return "_" + str((len(types) - 1) // 2) + "d"


def _argcountISuffix(types):
    '''`_i<N>` from parameter count, e.g. mx_hash_int(int,int) -> _i2.'''
    return "_i" + str(len(types))


# Base name -> suffix scheme. Overloaded families not listed use _firstTypeSuffix. Every entry
# is a GLSL-overloaded helper; the scheme reproduces the hand-written stdlib naming exactly.
SUFFIX_SCHEME = {
    "mx_square": _firstTypeSuffix,
    "mx_cell_noise_float": _firstTypeSuffix,
    "mx_cell_noise_vec3": _firstTypeSuffix,
    "mx_bilerp": _firstTypeSuffix,
    "mx_trilerp": _firstTypeSuffix,
    "mx_gradient_scale2d": _firstTypeSuffix,
    "mx_gradient_scale3d": _firstTypeSuffix,
    "mx_f0_to_ior": _firstTypeSuffix,   # vec3 form; the float form is a primary EXCEPTION below
    "mx_matrix_mul": _allTypesSuffix,
    "mx_perlin_noise_float": _vecDimSuffix,
    "mx_perlin_noise_vec3": _vecDimSuffix,
    "mx_worley_noise_float": _vecDimSuffix,
    "mx_worley_noise_vec2": _vecDimSuffix,
    "mx_worley_noise_vec3": _vecDimSuffix,
    "mx_worley_distance": _vecDimSuffix,
    "mx_gradient_float": _gradientDimSuffix,
    "mx_gradient_vec3": _gradientDimSuffix,
    "mx_worley_cell_position": _cellposDimSuffix,
    "mx_hash_int": _argcountISuffix,
    "mx_hash_vec3": _argcountISuffix,
}

# Individual overloads whose genwgsl name is semantic/irregular or a primary unsuffixed form. A
# None value marks a signature the genwgsl lib deliberately doesn't provide (node stays
# hand-written). Keyed exactly as buildContext extracts (name, GLSL param types).
EXCEPTIONS = {
    ("mx_f0_to_ior", ("float",)): "mx_f0_to_ior",

    ("mx_fresnel_schlick", ("float", "float")): "mx_fresnel_schlick_f32",
    ("mx_fresnel_schlick", ("float", "vec3")): "mx_fresnel_schlick_vec3",
    ("mx_fresnel_schlick", ("float", "float", "float")): "mx_fresnel_schlick_f32_f90",
    ("mx_fresnel_schlick", ("float", "vec3", "vec3")): "mx_fresnel_schlick_vec3_f90",
    ("mx_fresnel_schlick", ("float", "float", "float", "float")): "mx_fresnel_schlick_f32_exp",
    ("mx_fresnel_schlick", ("float", "vec3", "vec3", "float")): "mx_fresnel_schlick_vec3_exp",

    ("mx_ggx_dir_albedo", ("float", "float", "vec3", "vec3")): "mx_ggx_dir_albedo",
    ("mx_ggx_dir_albedo", ("float", "float", "float", "float")): "mx_ggx_dir_albedo_scalar",
    ("mx_ggx_dir_albedo", ("float", "float", "FresnelData")): "mx_ggx_dir_albedo_fresnel",
}

# Bases mangle() can resolve (drives call remapping). Every such base is GLSL-overloaded.
SUPPORTED_BASES = set(SUFFIX_SCHEME) | {b for (b, _t) in EXCEPTIONS}


def _isMapped(base, types):
    '''True if (base, types) has an explicit or scheme-derived genwgsl name.'''
    return (base, types) in EXCEPTIONS or base in SUFFIX_SCHEME


def mangle(name, types, overloaded):
    '''Return the genwgsl name for a GLSL overload, or None if intentionally unsupported.

    Resolution order: an explicit EXCEPTIONS entry, then the family's SUFFIX_SCHEME rule, else the
    name is returned unchanged (non-overloaded / not a renamed helper). An overloaded base with no
    scheme and no exception for this signature is unsupported (None), so the caller stays
    hand-written -- matching the previous CALL_MAP 'missing key' behavior.'''
    key = (name, types)
    if key in EXCEPTIONS:
        return EXCEPTIONS[key]
    scheme = SUFFIX_SCHEME.get(name)
    if scheme is not None:
        return name + scheme(types)
    if name in overloaded:
        return None
    return name


# -----------------------------------------------------------------------------
# lib transpilation tables
# -----------------------------------------------------------------------------

# Lib files where per-function transpile without in-file siblings fails because helpers call
# each other in the same file. These use transpileLibFileSiblings (transitive in-file
# callee bodies + overload-aware topo sort) instead of one-function-at-a-time.
LIB_USE_SIBLING_BODIES = {
    "mx_microfacet_specular", "mx_microfacet_sheen", "mx_flake", "mx_noise",
}

# Pin preprocessor branches to match current genwgsl behavior. Method 0 = analytic directional
# albedo (table/MC paths in microfacet libs are excluded from the WGSL port).
LIB_PREAMBLE = """
#define DIRECTIONAL_ALBEDO_METHOD 0
#define AIRY_FRESNEL_ITERATIONS 2
"""

# naga's GLSL frontend rejects `uniform sampler2D` and real texture ops in lib fragments.
# These stubs let the shader parse; only the function bodies we extract matter for output.
TEXTURE_STUB_PREAMBLE = """
vec3 mtlx_tex_lookup_rgb(vec2 uv, float lod) { return vec3(0.0); }
vec2 mtlx_tex_lookup_rg(vec2 uv) { return vec2(0.0); }
float mtlx_tex_lookup_b(vec2 uv) { return 0.0; }
float mtlx_tex_size_x() { return 256.0; }
"""

# naga's GLSL frontend requires a staged shader with an entry point; every wrapped fragment ends
# with this do-nothing fragment `main`. naga keeps the non-entry function bodies we actually want.
FRAG_MAIN_EPILOGUE = "\nlayout(location=0) out vec4 mtlx_o;\nvoid main() { mtlx_o = vec4(0.0); }\n"

# MaterialX $-tokens are not valid GLSL identifiers. Lib transpile expands a subset to
# naga-parseable GLSL stubs (NAGA_LIB_STUBS) before calling naga. Token *names* are validated
# against HwConstants.cpp (loadHwTokenNames); stub *values* are transpiler policy only.
#
# Replaces the former monolithic LIB_TOKEN_FIXUPS table: names come from the C++ generator,
# values stay here because naga needs parseable placeholders (sampler stubs, literal defaults).
NAGA_LIB_STUBS = {
    "$texSamplerSignature": "sampler2D mtlx_tex_sampler",
    "$texSamplerSampler2D": "mtlx_tex_sampler",
    "$albedoTable": "mtlx_albedo_table",
    "$albedoTableSize": "vec2(256.0)",
    "$envRadianceSamples": "16",
    "$envRadianceMips": "8",
    "$envMatrix": "mat4(1.0)",
    "$envRadiance": "mtlx_env_radiance_stub",
    "$envIrradiance": "mtlx_env_irradiance_stub",
    "$envLightIntensity": "vec3(1.0)",
    "$envPrefilterMip": "0.0",
    "$envRadianceSampler2D": "mtlx_tex_sampler",
    "$refractionTwoSided": "false",
}

# Struct types emitted centrally into mx_closure_type.wgsl (and skipped when transpiling other
# lib files). surfaceshader is emitted by WgslShaderGenerator::emitTypeDefinitions, not here.
# Layouts are derived from genglsl + GlslSyntax.cpp (wgslClosurePreamble), not hand-listed.
LIB_PREAMBLE_STRUCTS = {"surfaceshader", "ClosureData", "BSDF", "VDF", "FresnelData"}

# Aggregate/shader struct names parsed from MaterialXGenGlsl/GlslSyntax.cpp definition strings.
# Used by glslClosurePreamble (node context) and wgslClosurePreamble (BSDF/VDF only).
_GLSL_SYNTAX_STRUCT_NAMES = (
    "BSDF", "VDF", "surfaceshader", "volumeshader", "displacementshader", "lightshader",
)

# Set by main() before transpilation; used for preamble/token stub resolution.
_ACTIVE_LIBROOT = None

# Cached preambles keyed by resolved libroot path (replaces hand-written CLOSURE_PREAMBLE /
# LIB_STRUCT_PREAMBLE tables).
_WGSL_CLOSURE_PREAMBLE = {}
_GLSL_CLOSURE_PREAMBLE = {}

GLSL_TO_WGSL_TYPE = {
    # Used by transpileGlslStructs/consts when emitting WGSL struct/const preamble for lib files.
    "float": "f32", "int": "i32", "bool": "bool",
    "vec2": "vec2f", "vec3": "vec3f", "vec4": "vec4f",
    "mat2": "mat2x2f", "mat3": "mat3x3f", "mat4": "mat4x4f",
    "mat3x3": "mat3x3f", "mat2x2": "mat2x2f", "mat4x4": "mat4x4f",
}


# -----------------------------------------------------------------------------
# parsing
# -----------------------------------------------------------------------------

# These two scanners do depth-aware bracket matching so we can carve functions and argument lists
# out of source text without a full parser. They are the foundation the rest of the parsing relies
# on -- naga gives us no AST, so everything here is string surgery over balanced brackets.

def _matchBrace(text, i):
    '''Given index of an opening '{', return index just past the matching '}'.'''
    depth = 0
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return len(text)


def _matchParen(text, i):
    '''Given index of an opening '(', return the index OF the matching ')' (-1 if unbalanced).

    Note the asymmetry with _matchBrace: this returns the closing paren's own index (callers slice
    text[open+1:close] to get the contents), whereas _matchBrace returns one past the '}'.'''
    depth = 0
    while i < len(text):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


GLSL_KEYWORDS = {"if", "else", "for", "while", "switch", "do", "return", "case", "default"}


def _leadingComment(text, start):
    '''Return the comment block (//... or /*...*/) directly above the definition at `start`.

    Walks whole lines upward from the definition's line, collecting comment lines; stops at a blank
    line, a non-comment line, or the end of a previous definition. GLSL and WGSL comment syntax are
    identical, so the captured text is re-emitted verbatim (naga discards comments, so we preserve
    doc comments by re-attaching them here). Returns the block with a trailing newline, or '' when
    there is no contiguous comment directly above.'''
    lineStart = text.rfind("\n", 0, start) + 1
    lines = text[:lineStart].split("\n")
    if lines and lines[-1] == "":
        lines.pop()  # drop the empty element following the final newline
    collected = []
    inBlock = False  # walking upward inside a /* ... */ whose opener is on an earlier line
    for ln in reversed(lines):
        s = ln.strip()
        if inBlock:
            collected.append(ln)
            if s.startswith("/*"):
                inBlock = False
            continue
        if s == "":
            break
        if s.startswith("//"):
            collected.append(ln)
        elif s.endswith("*/"):
            collected.append(ln)
            if not s.startswith("/*"):
                inBlock = True
        else:
            break
    if inBlock or not collected:
        return ""  # unbalanced block, or nothing found -- emit nothing rather than a partial
    collected.reverse()
    return "\n".join(collected) + "\n"


def fileLeadComment(text):
    '''Return the file-level comment block at the very top of `text`, or ''.

    Only treated as a file-level comment when a blank line separates it from the code below;
    otherwise it is the leading doc comment of the first function and is captured as that
    function's 'lead' instead (avoids emitting it twice). Returned with a trailing blank line.'''
    m = re.match(r"((?:[ \t]*(?://[^\n]*|/\*.*?\*/)[ \t]*\n)+)", text, re.S)
    if not m:
        return ""
    if text[m.end():].startswith("\n"):
        return m.group(1).rstrip("\n") + "\n\n"
    return ""


def _stableAnchor(stmt):
    '''Pick a token from a GLSL statement likely to survive naga's restructuring, or None.

    Preference order (most to least stable): an assignment's LHS name, a distinctive mx_* call, a
    returned identifier. Pure literals are intentionally excluded -- they recur too often to place
    a comment reliably. Used only to re-anchor best-effort inline comments; a miss just drops the
    comment, never corrupts output.'''
    m = re.match(r"(?:[A-Za-z_]\w*\s+)?([A-Za-z_]\w*)\s*(?:\[[^\]]*\])?\s*=(?!=)", stmt)
    if m and m.group(1) not in GLSL_KEYWORDS:
        return m.group(1)
    m = re.search(r"\b(mx_\w+)\s*\(", stmt)
    if m:
        return m.group(1)
    m = re.match(r"return\s+([A-Za-z_]\w*)", stmt)
    if m and m.group(1) not in GLSL_KEYWORDS:
        return m.group(1)
    return None


def extractInlineComments(glslFull):
    '''Return [(anchor, [comment_line, ...])] for whole-line // comments inside a GLSL body.

    Each contiguous run of `// ...` lines is anchored to a stable token of the next statement, so
    it can be re-placed in naga's output. Best-effort: runs whose following statement has no stable
    anchor are dropped. Only whole-line comments are considered (trailing comments are ignored).'''
    groups = []
    pending = []
    started = False
    for ln in glslFull.split("\n"):
        s = ln.strip()
        if not started:
            if "{" in ln:
                started = True
            continue
        if s.startswith("//"):
            pending.append(s)
        elif s == "" or s.startswith("/*") or s.endswith("*/"):
            continue  # blank / block comment -- keep pending attached to the next statement
        elif pending:
            anchor = _stableAnchor(s)
            if anchor:
                groups.append((anchor, list(pending)))
            pending = []
    return groups


def injectInlineComments(glslFull, wgslText):
    '''Re-attach GLSL inline comments to the transpiled WGSL body (best-effort, never corrupting).

    naga discards comments and restructures bodies, so each comment run is placed on its own line(s)
    above the first WGSL line (at or after the previous placement) containing its anchor token.
    Anchors are matched monotonically so ordering is preserved and deterministic; an unmatched
    anchor's comments are dropped. Only whole-line insertion -- never mid-expression.'''
    groups = extractInlineComments(glslFull)
    if not groups:
        return wgslText
    lines = wgslText.split("\n")
    searchFrom = 1  # skip the `fn ...(` signature line
    inserts = []
    for anchor, comments in groups:
        pat = re.compile(r"\b" + re.escape(anchor) + r"\b")
        found = next((i for i in range(searchFrom, len(lines)) if pat.search(lines[i])), -1)
        if found < 0:
            continue  # deterministic drop
        inserts.append((found, comments))
        searchFrom = found + 1
    for idx, comments in reversed(inserts):
        indent = lines[idx][:len(lines[idx]) - len(lines[idx].lstrip())]
        for c in reversed(comments):
            lines.insert(idx, indent + c)
    if os.environ.get("MTLX_DEBUG"):
        dropped = len(groups) - len(inserts)
        if dropped:
            print(f"       inline comments: placed {len(inserts)}, dropped {dropped}")
    return "\n".join(lines)


def parseFunctions(text):
    '''Return [{ret, name, params, full, lead}] for every top-level function *definition*.

    Heuristic, not a real parser: we match the `<returnType> <name>(` shape, then confirm it is a
    definition (not a call or a prototype) by checking that a `{` follows the closing paren. The
    keyword filter rejects control-flow that looks like `<word> <word>(` (e.g. `else if (`), and the
    `{`-lookahead rejects prototypes ending in `;`. `full` is the entire definition text (signature
    through matching `}`) so callers can re-emit or wrap it; `lead` is the doc comment directly above
    the definition (re-attached after transpilation since naga discards comments).'''
    fns = []
    for m in re.finditer(r"\b([A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*\(", text):
        if m.group(1) in GLSL_KEYWORDS or m.group(2) in GLSL_KEYWORDS:
            continue  # control-flow construct (e.g. `else if (...) {`), not a definition
        openP = text.index("(", m.start(2))
        closeP = _matchParen(text, openP)
        if closeP < 0:
            continue
        # Skip whitespace after `)`; a definition has `{` here, a call/prototype has `;` or `,`.
        j = closeP + 1
        while j < len(text) and text[j].isspace():
            j += 1
        if j >= len(text) or text[j] != "{":
            continue  # a call/prototype, not a definition
        end = _matchBrace(text, j)
        fns.append({"ret": m.group(1), "name": m.group(2),
                    "params": text[openP + 1:closeP].strip(), "full": text[m.start(1):end],
                    "lead": _leadingComment(text, m.start(1))})
    return fns


def fnParamTypes(paramsStr):
    '''Extract bare GLSL parameter types from a parameter list string.'''
    types = []
    for p in paramsStr.split(","):
        p = re.sub(r"^\s*(const|in|out|inout)\s+", "", p.strip())
        if p:
            types.append(re.sub(r"\s+", " ",
                                re.sub(r"\s+[A-Za-z_]\w*\s*(\[\d*\])?$", "", p)).strip())
    return tuple(types)


def fnParamNames(paramsStr):
    '''Extract GLSL parameter identifiers from a parameter list string.'''
    names = []
    for p in paramsStr.split(","):
        p = re.sub(r"^\s*(const|in|out|inout)\s+", "", p.strip())
        if not p or "sampler2D" in p:
            continue
        tokens = p.split()
        if tokens:
            names.append(tokens[-1].split("[")[0])
    return names


def fnSigKey(fn):
    '''(name, param-types) identity for a parsed function; distinguishes overloads sharing a name.'''
    return (fn["name"], fnParamTypes(fn["params"]))


def expandLibTokens(text, libroot=None):
    '''Replace MaterialX $-tokens and texture/sampler calls with naga-parseable GLSL.

    Node transpile uses per-function MTLXTOK_* sentinels; lib transpile uses libTokenFixups()
    (NAGA_LIB_STUBS + $closureDataConstructor from HwConstants.cpp) plus the regex rewrites below
    that stub sampler types and texture ops naga's GLSL frontend cannot parse.'''
    if libroot is None:
        libroot = _activeLibroot()
    for rx, repl in libTokenFixups(libroot):
        text = rx.sub(repl, text)
    # Replace sampler types and texture ops with stubs naga accepts.
    text = re.sub(r"\bsampler2D\s+mtlx_\w+\b", "int mtlx_sampler_stub", text)
    text = re.sub(r"textureLod\s*\(\s*mtlx_tex_sampler\s*,\s*([^,]+),\s*([^)]+)\)",
                  r"mtlx_tex_lookup_rgb(\1, \2)", text)
    text = re.sub(r"texture\s*\(\s*mtlx_tex_sampler\s*,\s*([^)]+)\)\.xy",
                  r"mtlx_tex_lookup_rg(\1)", text)
    text = re.sub(r"texture\s*\(\s*mtlx_albedo_table\s*,\s*([^)]+)\)\.rg",
                  r"mtlx_tex_lookup_rg(\1)", text)
    text = re.sub(r"texture\s*\(\s*mtlx_albedo_table\s*,\s*([^)]+)\)\.b",
                  r"mtlx_tex_lookup_b(\1)", text)
    text = re.sub(r"textureSize\s*\(\s*mtlx_tex_sampler\s*,\s*0\s*\)",
                  r"vec2(256.0)", text)
    text = re.sub(r"textureSize\s*\(\s*mtlx_albedo_table\s*,\s*0\s*\)\.x",
                  r"mtlx_tex_size_x()", text)
    text = re.sub(r"textureSize\s*\(\s*mtlx_env_radiance_stub\s*,\s*0\s*\)\.x",
                  r"mtlx_tex_size_x()", text)
    text = re.sub(r"texture\s*\(\s*mtlx_env_radiance_stub\s*,\s*([^)]+)\)\.rgb",
                  r"mtlx_tex_lookup_rgb(\1, 0.0)", text)
    text = re.sub(r"texture\s*\(\s*mtlx_env_irradiance_stub\s*,\s*([^)]+)\)\.rgb",
                  r"mtlx_tex_lookup_rgb(\1, 0.0)", text)
    text = re.sub(r"mx_latlong_map_lookup\s*\(([^,]+),\s*([^,]+),\s*([^,]+),\s*mtlx_env_radiance_stub\s*\)",
                  r"mtlx_tex_lookup_rgb(vec2(0.0), \3)", text)
    text = re.sub(r"mx_latlong_map_lookup\s*\(([^,]+),\s*([^,]+),\s*([^,]+),\s*mtlx_env_irradiance_stub\s*\)",
                  r"mtlx_tex_lookup_rgb(vec2(0.0), \3)", text)
    return text


def wgslFnName(glslName, types, overloaded):
    '''Return the genwgsl function name for a GLSL overload.

    Delegates to mangle(): scheme/exception families are renamed (e.g. mx_square -> mx_square_f32),
    everything else is unchanged. Used for lib *definitions*; remapCalls() applies the same map to
    node *calls*. A None result (intentionally unsupported) falls back to the plain name here, since
    a definition always needs a name; unsupported *calls* are handled in remapCalls.'''
    return mangle(glslName, types, overloaded) or glslName


def denagaName(text, knownNames, collisions=True):
    '''Reverse naga's identifier renaming for symbols the transpiler re-emits with clean names.

    naga's `Namer::call` (proc/namer.rs) rewrites an identifier deterministically: the first use of
    a sanitized base gets a trailing `_` iff it ends in a digit or is a keyword/builtin, and any
    later collision with an already-used name gets `_<N>`. Our declarations (consts, struct fields,
    prototypes) keep the clean GLSL spelling, so references naga emitted as `NAME_` or `NAME_<N>`
    must be mapped back to `NAME`.

    - collisions=True  handles both `NAME_` (digit/keyword rule) and `NAME_<N>` (collision rule);
      use for consts/fields naga may see more than once.
    - collisions=False handles only the single trailing `_`; use for names where a `_<N>` form is a
      *distinct* symbol that must be preserved (e.g. overloaded function stubs mx_foo_1, remapped
      elsewhere).

    Longest name first so a shorter symbol can't capture a longer one's suffix; a suffixed token
    that is itself a known name (e.g. FUJII_CONSTANT_1) is left untouched. Only listed names are
    keyed, so naga's numbered *locals* are unaffected.'''
    names = set(n for n in knownNames if n)
    suffix = r"_\d*" if collisions else r"_"
    for nm in sorted(names, key=len, reverse=True):
        text = re.sub(r"\b" + re.escape(nm) + suffix + r"\b",
                      lambda m: m.group(0) if m.group(0) in names else nm, text)
    return text


def applyFieldRenames(text, libroot=None):
    '''Reverse naga's ends-in-digit `_` on struct fields declared in the closure preamble.

    FresnelData fields F0/F82/F90 end in a digit; naga suffixes references (F0_) but our preamble
    re-emits the clean names. Digit-field names are discovered from wgslClosurePreamble() rather
    than a hand-maintained list. The former tf_* -> thinfilm_* rename was removed: GLSL FresnelData
    now uses thinfilm_* field names directly (mx_microfacet_specular.glsl).'''
    if libroot is None:
        libroot = _activeLibroot()
    return denagaName(text, preambleDigitFields(libroot), collisions=False)


def resolveConstRefs(text, constNames):
    '''Rewrite naga-suffixed references to module-scope consts back to their declared name.

    buildContext puts every lib const in naga's parse context, and the sibling-body path *also*
    emits the file's preamble into the wrapped fragment, so naga sees `FRESNEL_MODEL_SCHLICK` twice
    and renames body references to `FRESNEL_MODEL_SCHLICK_1`; a digit-ending const like
    FUJII_CONSTANT_1 becomes FUJII_CONSTANT_1_. Delegates to denagaName() (both the digit/keyword
    and collision rules apply to consts).'''
    return denagaName(text, constNames, collisions=True)


def constNamesFromWgsl(consts):
    '''Names of `const NAME: T = ...` declarations (WGSL form, from transpileGlslConsts).'''
    return [m.group(1) for c in consts for m in [re.match(r"const (\w+):", c)] if m]


def glslConstNames(glslText):
    '''Names of file-scope `const TYPE NAME = ...` declarations in GLSL context text (e.g. base).'''
    return re.findall(r"\bconst\s+[\w<>]+\s+([A-Za-z_]\w*)\s*=", glslText)


def glslTypeToWgsl(typename):
    return GLSL_TO_WGSL_TYPE.get(typename, typename)


# -----------------------------------------------------------------------------
# derived preambles & token registry
# -----------------------------------------------------------------------------
#
# Closure struct layouts and MaterialX $-token handling were previously duplicated as hand-written
# tables (CLOSURE_PREAMBLE, LIB_STRUCT_PREAMBLE, LIB_TOKEN_FIXUPS, LIB_FIELD_RENAMES). These helpers
# derive the same output from the canonical C++/GLSL sources so genglsl and the WGSL generator stay
# the single source of truth.


def setActiveLibroot(libroot):
    '''Record the libraries root for preamble/token resolution (called from main()).

    libroot is typically `libraries/`; repo-relative paths (HwConstants.cpp, GlslSyntax.cpp,
    genglsl/lib/*.glsl) are resolved via _repoRoot().'''
    global _ACTIVE_LIBROOT
    _ACTIVE_LIBROOT = Path(libroot).resolve()


def _activeLibroot():
    '''Return the libroot set by setActiveLibroot(); required before any preamble/token helper.'''
    if _ACTIVE_LIBROOT is None:
        raise RuntimeError("setActiveLibroot() must be called before transpilation")
    return _ACTIVE_LIBROOT


def _repoRoot(libroot):
    '''Parent of libroot (the MaterialX repo root when libroot is `libraries/`).'''
    return Path(libroot).resolve().parent


def _readSourceText(path):
    '''Read a repo source file as UTF-8 text.'''
    return path.read_text(encoding="utf-8")


def loadHwTokenNames(libroot):
    '''Return every MaterialX $-token name declared in HwConstants.cpp (T_* constants).

    Used by validateTokenCoverage to ensure lib GLSL only references tokens the C++ generator
    knows about. Does not include stub values -- those are transpiler policy (NAGA_LIB_STUBS).'''
    path = _repoRoot(libroot) / "source" / "MaterialXGenHw" / "HwConstants.cpp"
    if not path.is_file():
        return set()
    text = _readSourceText(path)
    return set(re.findall(r'const string T_\w+\s*=\s*"(\$[^"]+)"', text))


def nagaLibStubs(libroot):
    '''Merge NAGA_LIB_STUBS with HwConstants values needed for naga-parseable lib transpile.

    Currently adds $closureDataConstructor (the makeClosureData function name string) so lib
    sources using that token expand to a real GLSL identifier before naga runs.'''
    stubs = dict(NAGA_LIB_STUBS)
    hw = _repoRoot(libroot) / "source" / "MaterialXGenHw" / "HwConstants.cpp"
    if hw.is_file():
        text = _readSourceText(hw)
        m = re.search(r'const string CLOSURE_DATA_CONSTRUCTOR\s*=\s*"([^"]+)"', text)
        if m:
            stubs["$closureDataConstructor"] = m.group(1)
    return stubs


def libTokenFixups(libroot):
    '''(compiled_regex, replacement) pairs for expandLibTokens, longest token first.

    Longest-first ordering prevents a short $-token prefix from partially matching a longer one
    (e.g. $texSampler vs $texSamplerSignature).'''
    stubs = nagaLibStubs(libroot)
    return [(re.compile(re.escape(tok)), repl)
            for tok, repl in sorted(stubs.items(), key=lambda x: len(x[0]), reverse=True)]


def loadGlslSyntaxSnippets(repoRoot):
    '''Extract struct and #define snippets from MaterialXGenGlsl/GlslSyntax.cpp.

    Parses the AggregateTypeSyntax definition strings (BSDF, VDF, surfaceshader, etc.) and the
    EDF/material aliases exactly as the GLSL generator emits them. Node transpile uses the full set;
    wgslClosurePreamble uses BSDF/VDF only (ClosureData/FresnelData come from genglsl/lib).'''
    path = repoRoot / "source" / "MaterialXGenGlsl" / "GlslSyntax.cpp"
    text = _readSourceText(path)
    snippets = {}
    for name in _GLSL_SYNTAX_STRUCT_NAMES:
        m = re.search(rf'"struct {name} \{{[^"]+\}};"', text)
        if m:
            snippets[name] = m.group(0).strip('"')
    for key, pattern in (("EDF", r'"#define EDF vec3"'),
                         ("material", r'"#define material surfaceshader"')):
        m = re.search(pattern, text)
        if m:
            snippets[key] = m.group(0).strip('"')
    return snippets


def _emitWgslStructsFromGlsl(text, only=None, skip=None):
    '''Convert selected GLSL struct definitions in `text` to WGSL struct blocks.

    Shared by wgslClosurePreamble and transpileGlslStructs. Strips GLSL comments, maps scalar/
    vector types via GLSL_TO_WGSL_TYPE, and rewrites array fields (`name[N]` -> `array<T, N>`).
    When `only` is set, emit just those struct names (used to pull ClosureData/FresnelData from lib
    files without re-emitting every struct in the source). When `skip` is set, omit those names
    (used to drop closure structs provided centrally by wgslClosurePreamble).'''
    out = []
    for m in re.finditer(r"\bstruct\s+(\w+)\s*\{([^}]*)\}\s*;?", text):
        name = m.group(1)
        if only is not None and name not in only:
            continue
        if skip is not None and name in skip:
            continue
        bodySrc = re.sub(r"/\*.*?\*/", "", m.group(2), flags=re.S)
        bodySrc = re.sub(r"//[^\n]*", "", bodySrc)
        fields = []
        for part in bodySrc.split(";"):
            part = part.strip()
            if not part:
                continue
            tokens = part.split()
            if len(tokens) < 2:
                continue
            ftype, fname = tokens[0], tokens[1]
            wtype = glslTypeToWgsl(ftype)
            arr = re.match(r"(\w+)\[(\d+)\]$", fname)
            if arr:
                fname, wtype = arr.group(1), f"array<{wtype}, {arr.group(2)}>"
            fields.append(f"    {fname}: {wtype},")
        if fields:
            body = "\n".join(fields).rstrip(",")
            out.append(f"struct {name} {{\n{body}\n}}")
    return out


def _buildWgslClosurePreamble(libroot):
    '''Build the WGSL struct preamble prepended to mx_closure_type.wgsl.

    Replaces the former LIB_STRUCT_PREAMBLE hand-written block. Sources:
      - ClosureData  from libraries/pbrlib/genglsl/lib/mx_closure_type.glsl
      - BSDF, VDF    from GlslSyntax.cpp (same layout as GLSL generator)
      - EDF, material aliases (vec3f / surfaceshader)
      - FresnelData  from libraries/pbrlib/genglsl/lib/mx_microfacet_specular.glsl
    surfaceshader is omitted here (WgslShaderGenerator::emitTypeDefinitions owns it).'''
    libroot = Path(libroot).resolve()
    repo = _repoRoot(libroot)
    parts = []
    closureSrc = _readSourceText(libroot / "pbrlib" / "genglsl" / "lib" / "mx_closure_type.glsl")
    specSrc = _readSourceText(libroot / "pbrlib" / "genglsl" / "lib" / "mx_microfacet_specular.glsl")
    parts.extend(_emitWgslStructsFromGlsl(closureSrc, only={"ClosureData"}))
    snippets = loadGlslSyntaxSnippets(repo)
    for name in ("BSDF", "VDF"):
        parts.extend(_emitWgslStructsFromGlsl(snippets[name]))
    parts.append("alias EDF = vec3f;")
    parts.append("alias material = surfaceshader;")
    parts.extend(_emitWgslStructsFromGlsl(specSrc, only={"FresnelData"}))
    return "\n\n".join(parts) + "\n"


def wgslClosurePreamble(libroot):
    '''Cached WGSL closure preamble for mx_closure_type.wgsl (see _buildWgslClosurePreamble).'''
    key = str(Path(libroot).resolve())
    if key not in _WGSL_CLOSURE_PREAMBLE:
        _WGSL_CLOSURE_PREAMBLE[key] = _buildWgslClosurePreamble(libroot)
    return _WGSL_CLOSURE_PREAMBLE[key]


def _buildGlslClosurePreamble(libroot):
    '''Build the GLSL type preamble injected into node transpile context (buildContext).

    Replaces the former CLOSURE_PREAMBLE constant. Emits every aggregate/shader struct and the
    EDF/material #defines from GlslSyntax.cpp so node fragments can reference BSDF, surfaceshader,
    etc. without #include-ing the full lib tree.'''
    repo = _repoRoot(libroot)
    snippets = loadGlslSyntaxSnippets(repo)
    lines = [snippets[n] for n in _GLSL_SYNTAX_STRUCT_NAMES]
    lines.append(snippets["EDF"])
    lines.append(snippets["material"])
    return "\n".join(lines) + "\n"


def glslClosurePreamble(libroot):
    '''Cached GLSL closure preamble for node transpile (see _buildGlslClosurePreamble).'''
    key = str(Path(libroot).resolve())
    if key not in _GLSL_CLOSURE_PREAMBLE:
        _GLSL_CLOSURE_PREAMBLE[key] = _buildGlslClosurePreamble(libroot)
    return _GLSL_CLOSURE_PREAMBLE[key]


def preambleDigitFields(libroot):
    '''Field names ending in a digit in the WGSL closure preamble (for denagaName).

    Scans wgslClosurePreamble() output so F0/F82/F90 (and any future digit-ending fields) are
    reconciled automatically when the derived preamble changes.'''
    return sorted(set(re.findall(r"^\s*(\w*\d)\s*:", wgslClosurePreamble(libroot), re.M)))


def transpileGlslStructs(text):
    '''Convert top-level GLSL struct definitions to WGSL (emitted above lib fn bodies).

    Skips types provided centrally by wgslClosurePreamble (see LIB_PREAMBLE_STRUCTS). Delegates
    to _emitWgslStructsFromGlsl, which strips GLSL comments before splitting fields (otherwise a
    comment word is read as a `type name` pair) and rewrites array fields to WGSL.'''
    return _emitWgslStructsFromGlsl(text, skip=LIB_PREAMBLE_STRUCTS)


def transpileGlslConsts(text):
    '''Convert file-scope GLSL `const T name = ...` to WGSL `const name: T = ...` syntax.

    Only *top-level* consts are emitted. Function-local consts (e.g. the `const int SAMPLE_COUNT`
    inside several directional-albedo helpers) are handled by naga inside the transpiled bodies;
    hoisting them here would produce duplicate module-scope consts -- and since the same name
    recurs across microfacet libs, redeclaration errors once several are included together. Blank
    out function bodies first so their indented consts aren't matched by the file-scope regex.'''
    scope = text
    for fn in parseFunctions(text):
        scope = scope.replace(fn["full"], "")
    out = []
    for m in re.finditer(r"^\s*const\s+(\w+)\s+(\w+)\s*=\s*([^;]+);", scope, re.M):
        out.append(f"const {m.group(2)}: {glslTypeToWgsl(m.group(1))} = {m.group(3)};")
    return out


def libIncludes(text):
    '''Return #include paths from a lib file (lib/... only).'''
    return [inc for inc in re.findall(r'#include\s+"([^"]+)"', text)
            if inc.startswith("lib/")]


def stripIncludes(text):
    '''Remove whole `#include "..."` lines (naga sees inlined bodies, not include directives).'''
    return re.sub(r'#include\s+"[^"]+"\s*\n', "", text)


def generatedBanner(srcRel):
    '''The two-line "generated, do not edit" header prepended to every emitted .wgsl file.'''
    return (f"// Generated from {srcRel} by source/MaterialXGenWgsl/tools/mxgenwgsl.py.\n"
            f"// Do not edit -- re-run the transpiler to regenerate "
            f"(see source/MaterialXGenWgsl/README.md).\n\n")


def writeGenerated(outPath, content, label):
    '''Create parent dirs, write a generated .wgsl file, and log its OK line.'''
    outPath.parent.mkdir(parents=True, exist_ok=True)
    outPath.write_text(content, encoding="utf-8")
    print(f"  OK   {label} -> {outPath}")


def topoSortLibFiles(libFiles):
    '''Topological sort of lib/*.glsl by `#include \"lib/...\"` dependencies.

    Ensures mx_microfacet.glsl is processed before mx_microfacet_specular.glsl, etc., so
    generated genwgsl/lib/*.wgsl includes resolve when nodes are transpiled later.'''
    stems = {f.stem: f for f in libFiles}
    deps = {}
    for f in libFiles:
        txt = f.read_text(encoding="utf-8")
        deps[f.stem] = {Path(inc).stem for inc in libIncludes(txt) if Path(inc).stem in stems}
    order, seen = [], set()

    def visit(stem):
        if stem in seen:
            return
        seen.add(stem)
        for d in sorted(deps.get(stem, ())):
            visit(d)
        order.append(stems[stem])

    for stem in sorted(stems):
        visit(stem)
    return order


def postprocessWgslFn(text, fnName, protos, overloaded, libSymbols=None, remap=True,
                        glslParamNames=None):
    '''Shared post-processing for one transpiled WGSL function (lib or node).

    Runs cleanup, type normalization, overload remapping, and optional lib arity checks.
    Returns (text, []) on success or (None, unsupported_calls) when remap/arity fails.'''
    text = cleanupFunction(text, glslParamNames)
    for rx, repl in TYPE_FIXUPS:
        text = rx.sub(repl, text)
    text = re.sub(r"\b(\d+\.\d+(?:[eE][-+]?\d+)?)f\b", r"\1", text)
    text = re.sub(r"(?<![\w.])(\d+)f\b", r"\1.0", text)
    # Strip naga's single trailing `_` off re-emitted prototype names (its ends-in-digit/keyword
    # rule). Overload collision stubs (mx_foo_1) are a distinct symbol handled by remap, so keep
    # collisions=False here.
    text = denagaName(text, {nm for (nm, _t) in protos}, collisions=False)
    text = applyFieldRenames(text)
    if remap:
        text, unsupported = remapCalls(text, fnName, protos, overloaded)
        if libSymbols is not None:
            unsupported += checkLibArity(text, libSymbols)
        if unsupported:
            return None, unsupported
    return text, []


def nagaTranspileGlsl(glslSrc, debugPath=None):
    '''Run naga on a complete GLSL fragment shader; return (WGSL text, None) or (None, error).

    When MTLX_DEBUG is set, callers may pass debugPath to persist the failing GLSL input.'''
    with tempfile.TemporaryDirectory() as td:
        frag = Path(td) / "in.frag"
        wtmp = Path(td) / "out.wgsl"
        frag.write_text(glslSrc, encoding="utf-8")
        r = subprocess.run([NAGA, "--input-kind", "glsl", "--shader-stage", "frag",
                            str(frag), str(wtmp)], capture_output=True, text=True)
        if r.returncode != 0:
            if debugPath:
                debugPath.parent.mkdir(parents=True, exist_ok=True)
                debugPath.write_text(glslSrc, encoding="utf-8")
            err = next((l for l in r.stderr.splitlines() if "error" in l.lower()), "naga error")
            return None, err.strip()
        return wtmp.read_text(encoding="utf-8"), None


# naga renders GLSL scalar/vector/matrix types in this canonical form; used to match a target
# overload's GLSL parameter types against a naga output function's signature.
GLSL_TO_NAGA_TYPE = {
    "float": "f32", "int": "i32", "uint": "u32", "bool": "bool",
    "vec2": "vec2<f32>", "vec3": "vec3<f32>", "vec4": "vec4<f32>",
    "ivec2": "vec2<i32>", "ivec3": "vec3<i32>", "ivec4": "vec4<i32>",
    "uvec2": "vec2<u32>", "uvec3": "vec3<u32>", "uvec4": "vec4<u32>",
    "mat2": "mat2x2<f32>", "mat3": "mat3x3<f32>", "mat4": "mat4x4<f32>",
}


def _wgslSigTypes(fnText):
    '''Parameter types from a (raw naga) WGSL fn signature, e.g. ('f32', 'vec3<f32>').'''
    sig = re.match(r"fn\s+\w+\s*\(([^)]*)\)", fnText, re.S)
    if not sig:
        return ()
    out = []
    for p in sig.group(1).split(","):
        m = re.match(r"[A-Za-z_]\w*\s*:\s*(.+)", p.strip(), re.S)
        if m:
            out.append(re.sub(r"\s+", "", m.group(1)))
    return tuple(out)


def extractTranspiledFn(wgsl, glslName, wgslName, glslTypes=None):
    '''Pull one non-stub function from naga output and rename to the target genwgsl name.

    Per-function lib/node transpile feeds naga a module with one real body; this extracts that
    body and renames it (e.g. mx_square -> mx_square_f32) via wgslFnName. When several same-named
    overloads appear in one naga module (sibling path, e.g. mx_ggx_dir_albedo's vec3, scalar, and
    FresnelData forms), `glslTypes` disambiguates by matching the parameter signature; with a single
    candidate the base-name match is used directly (signature match is skipped, since naga rewrites
    `out` params to pointers and would otherwise not compare equal).'''
    cands = [(name, t) for name, t in topLevelFns(wgsl)
             if fnBase(name) == glslName and "{\n}" not in t and t.count("\n") > 1]
    if not cands:
        return None
    chosen = cands[0]
    if len(cands) > 1 and glslTypes is not None:
        want = tuple(GLSL_TO_NAGA_TYPE.get(t, t) for t in glslTypes)
        chosen = next(((n, t) for n, t in cands if _wgslSigTypes(t) == want), cands[0])
    name, t = chosen
    return re.sub(r"(\bfn\s+)" + re.escape(name) + r"\b", r"\1" + wgslName, t)


# Closure/shader types for node transpile are built from GlslSyntax.cpp (glslClosurePreamble).
# WGSL lib types for mx_closure_type.wgsl use wgslClosurePreamble (genglsl/lib + GlslSyntax.cpp).


def nagaProtoParams(paramsStr):
    '''Normalize GLSL prototype params for naga: strip the semantically-neutral `const`/`in`
    qualifiers, KEEP `out`/`inout`, and drop sampler params naga's prototype parser rejects.

    Keeping `out`/`inout` is essential: naga renders those params as `ptr<function, T>`, and when it
    transpiles a *caller* it must see the callee's prototype as by-pointer so it passes the pointer
    (e.g. `mx_normalmap_vector2(..., result)`) rather than dereferencing it (`(*result)`), which
    would mismatch the transpiled definition's pointer parameter. naga accepts `out`/`inout` in a
    forward declaration.'''
    parts = []
    for p in paramsStr.split(","):
        p = p.strip()
        p = re.sub(r"^const\s+", "", p)   # const: no call-site effect
        p = re.sub(r"^in\s+", "", p)      # `in` is the default (by value); `\s+` guards `int`/`inout`
        if not p or "sampler2D" in p:
            continue
        parts.append(p)
    return ", ".join(parts)


def buildContext(libroot, libs, nodes=True):
    '''Build the naga parse context. Returns (base, protos, overloaded):
      base       - glslClosurePreamble + dedup'd #defines/consts/struct-defs from every genglsl lib.
      protos     - {(name, types): "prototype;"} for every function defined in any genglsl lib OR
                   node file, so helpers AND cross-node calls (e.g. mx_burn_color3 -> mx_burn_float)
                   and generator-supplied helpers (mx_environment_radiance) all resolve.
      overloaded - the set of names appearing with more than one signature (informational; the
                   actual overload remapping is driven by mangle() in remapCalls).
    Per node we emit `base` + every prototype except the one being defined.

    Pass nodes=False for lib transpilation: skip mx_*.glsl node files (their `inout` protos break
    naga) and omit glslClosurePreamble (lib bodies are inlined whole; closure types come from
    wgslClosurePreamble in mx_closure_type.wgsl only).'''
    defines, consts, structs, protos = {}, {}, {}, {}
    # Scan lib/ helpers and the node files themselves (the latter for cross-node prototypes).
    sources = []
    for lib in libs:
        gldir = libroot / lib / "genglsl"
        if gldir.is_dir():
            sources += sorted((gldir / "lib").glob("*.glsl"))
            if nodes:
                # Node files too (for cross-node prototypes), minus the skipped ones (light shaders
                # reference the dynamic LightData struct; texture nodes carry $-tokens).
                sources += [f for f in sorted(gldir.glob("mx_*.glsl"))
                            if not any(p.search(f.stem) for p in SKIP_PATTERNS)]
    # Collect #defines, consts, struct definitions, and function prototypes across all sources.
    # `setdefault` keeps the first occurrence, so a symbol defined in several files is deduped.
    for f in sources:
        txt = f.read_text(encoding="utf-8")
        for l in txt.splitlines():
            m = re.match(r"#define\s+(\w+)", l.lstrip())
            if m:
                defines.setdefault(m.group(1), l.strip())
        for m in re.finditer(r"^\s*const\s+[\w<>]+\s+(\w+)\s*=[^;{]*;", txt, re.M):
            consts.setdefault(m.group(1), m.group(0).strip())
        for m in re.finditer(r"\bstruct\s+(\w+)\s*\{[^}]*\}\s*;?", txt):
            structs.setdefault(m.group(1), m.group(0))
        for fn in parseFunctions(txt):
            types = fnParamTypes(fn["params"])
            protos.setdefault((fn["name"], types),
                              f"{fn['ret']} {fn['name']}({nagaProtoParams(fn['params'])});")
    baseItems = list(defines.values()) + list(consts.values()) + list(structs.values())
    # Node context needs closure/shader types from GlslSyntax.cpp; lib-only pass skips them.
    preamble = glslClosurePreamble(libroot) if nodes else ""
    base = preamble + "\n".join(s for s in baseItems if "$" not in s)
    protos = {k: v for k, v in protos.items() if "$" not in v}
    # Names with more than one signature are GLSL-overloaded. WGSL has no overloading and the
    # hand-written genwgsl lib renames/consolidates these (e.g. mx_square_f32, a single
    # mx_ggx_dir_albedo), so the util cannot guarantee a transpiled call resolves against the lib.
    protoNames = [nm for (nm, _t) in protos]
    overloaded = {nm for nm in protoNames if protoNames.count(nm) > 1}
    return base, protos, overloaded


# -----------------------------------------------------------------------------
# cleanup (see mxwgslcleanup.py)
# -----------------------------------------------------------------------------
#
# Param-copy shadow collapse lives in mxwgslcleanup (tree-sitter). inlineSingleUseTemps runs there
# after collapse; nothing else to define in this module.


def _countItems(s, brackets="()[]<>"):
    '''Count top-level comma-separated items in `s` (0 if blank), ignoring commas nested inside
    the given bracket pairs.'''
    s = s.strip()
    if not s:
        return 0
    opens = brackets[0::2]
    closes = brackets[1::2]
    depth = 0
    n = 1
    for ch in s:
        if ch in opens:
            depth += 1
        elif ch in closes:
            depth = max(0, depth - 1)
        elif ch == "," and depth == 0:
            n += 1
    return n


def buildWgslLibSymbols(libroot, libs, outroot=None):
    '''Parse genwgsl `lib/` files into {function name: parameter count}.

    Reads from `outroot` when set (post-generation), else `libroot` (legacy hand-written tree).
    '''
    symbols = {}
    root = outroot if outroot is not None else libroot
    for lib in libs:
        wdir = root / lib / "genwgsl" / "lib"
        if not wdir.is_dir():
            continue
        for f in sorted(wdir.glob("*.wgsl")):
            txt = f.read_text(encoding="utf-8")
            for m in re.finditer(r"\bfn\s+([A-Za-z_]\w*)\s*\(", txt):
                op = txt.index("(", m.start())
                cp = _matchParen(txt, op)
                if cp >= 0:
                    symbols[m.group(1)] = _countItems(txt[op + 1:cp])
    return symbols


def checkLibArity(text, libSymbols):
    '''Return a list of calls whose arg count disagrees with the genwgsl lib's parameter count.'''
    bad = []
    for m in re.finditer(r"\b(mx_\w+)\s*\(", text):
        name = m.group(1)
        if name not in libSymbols:
            continue  # cross-node helper, builtin, or the node's own fn -- not a lib symbol
        op = text.index("(", m.start())
        cp = _matchParen(text, op)
        if cp < 0:
            continue
        nargs = _countItems(text[op + 1:cp], "()[]")  # call args: no generics, keep '<'/'>' literal
        if nargs != libSymbols[name]:
            bad.append(f"{name} (call has {nargs}, lib expects {libSymbols[name]})")
    return bad


# -----------------------------------------------------------------------------
# scan-driven validation
# -----------------------------------------------------------------------------
#
# These run off the same scan buildContext performs, so gaps between genglsl and the mangling
# tables (or the genwgsl lib) surface loudly instead of silently mis-emitting a name.

def validateOverloadCoverage(protos, overloaded):
    '''Return sorted overloaded (name, types) that mangle() cannot resolve.

    Every GLSL-overloaded helper must map to a genwgsl name (scheme or exception); an unresolved
    overload would leak naga's `_N`-suffixed name into the output. A genuinely unsupported overload
    should be an explicit `None` in EXCEPTIONS (which this treats as covered).'''
    missing = []
    for key in sorted(protos):
        name, types = key
        if name in overloaded and key not in EXCEPTIONS and mangle(name, types, overloaded) is None:
            missing.append(key)
    return missing


def validateTokenCoverage(libroot, libs):
    '''Return $-tokens in transpiled genglsl/lib sources missing from HwConstants or NAGA_LIB_STUBS.

    Two-tier check (replaces a single hand-maintained LIB_TOKEN_FIXUPS list):
      1. Token must be declared in HwConstants.cpp (loadHwTokenNames) -- same names the C++
         generator substitutes at shader link time.
      2. If the lib file is transpiled (not hand-written), token must also have a naga
         stub (nagaLibStubs) so expandLibTokens can produce parseable GLSL before naga runs.
    Hand-written lib files (skip_transpile.txt) are skipped (they are not fed to naga).'''
    known = loadHwTokenNames(libroot)
    stubs = set(nagaLibStubs(libroot))
    unhandled = {}
    for lib in libs:
        gllib = libroot / lib / "genglsl" / "lib"
        if not gllib.is_dir():
            continue
        for f in sorted(gllib.glob("*.glsl")):
            if isHandWrittenLib(lib, f.stem):
                continue
            txt = f.read_text(encoding="utf-8")
            for tok in re.findall(r"\$[A-Za-z_]\w*", txt):
                if tok not in known:
                    unhandled.setdefault(tok, f"{f.name} (unknown to HwConstants)")
                elif tok not in stubs:
                    # Declared in C++ but no naga-parseable stub for lib transpile.
                    unhandled.setdefault(tok, f"{f.name} (no NAGA stub)")
    return unhandled


def validateLibNames(protos, libSymbols):
    '''Return mangle() targets that are absent from the genwgsl lib symbol table.

    libSymbols should union the generated output and the hand-written stdlib names, so a scheme
    that produces a name the real lib does not define (e.g. after a hand-written rename) fails
    loudly. Overloads mangle() marks unsupported (None) are skipped -- their nodes stay hand-written.'''
    missing = []
    for (name, types) in sorted(protos):
        if name not in SUPPORTED_BASES:
            continue
        target = mangle(name, types, {name})  # name treated as overloaded for resolution
        if target and target not in libSymbols:
            missing.append(f"{name}{types} -> {target}")
    return missing


def remapCalls(text, nodeFnName, protos, overloaded):
    '''Rewrite overloaded/diverged helper calls to their genwgsl names via mangle().

    naga numbers overload stubs (`mx_foo`, `mx_foo_1`, ...) by prototype-declaration order, and
    protoBlock is emitted sorted by (name, types), so the i-th call name corresponds to the i-th
    entry of the base's sorted type list. Returns (text, unsupported) where unsupported lists any
    call mangle() resolves to None -- the caller fails the node so it stays hand-written.
    '''
    byBase = {}
    for (nm, types) in protos:
        byBase.setdefault(nm, []).append(types)
    for nm in byBase:
        byBase[nm] = sorted(byBase[nm])

    unsupported = []
    for base in sorted(SUPPORTED_BASES, key=len, reverse=True):
        if base == nodeFnName or base not in byBase:
            continue
        for i, types in enumerate(byBase[base]):
            callname = base if i == 0 else f"{base}_{i}"
            if not re.search(r"\b" + re.escape(callname) + r"\s*\(", text):
                continue
            target = mangle(base, types, overloaded)
            if not target:  # None (adapted) or unmapped overload -> keep hand-written
                unsupported.append(callname + "(" + ", ".join(types) + ")")
                continue
            text = re.sub(r"\b" + re.escape(callname) + r"\s*\(", target + "(", text)
    return text, unsupported


# naga's canonical type spelling -> GLSL type used to key the mangle tables (inverse of
# GLSL_TO_NAGA_TYPE).
NAGA_TO_GLSL_TYPE = {v: k for k, v in GLSL_TO_NAGA_TYPE.items()}


def remapCallsByNagaSig(text, wgslModule, selfBase, overloaded):
    '''Remap overloaded helper calls using the signatures naga actually assigned in wgslModule.

    The sibling-body path defines several overloads of a name in one module, and naga numbers the
    stubs (`mx_foo`, `mx_foo_1`, ...) in an order that depends on its internal processing -- not the
    sorted-proto order remapCalls assumes. Rather than guess the index, read each naga function's
    real parameter signature straight from the module, recover its GLSL types, and resolve
    (base, types) through mangle(). Longest names first so `mx_foo_1` isn't clobbered by `mx_foo`.
    `selfBase` is the target's own name (skip, so a recursive call isn't misrouted). Returns
    (text, unsupported) where unsupported lists calls mangle() resolves to None.'''
    sigs = {}
    for name, t in topLevelFns(wgslModule):
        wt = _wgslSigTypes(t)
        sigs[name] = tuple(NAGA_TO_GLSL_TYPE.get(x, x) for x in wt)
    unsupported = []
    for name in sorted(sigs, key=len, reverse=True):
        base = fnBase(name)
        if base == selfBase or base not in SUPPORTED_BASES:
            continue
        if not re.search(r"\b" + re.escape(name) + r"\s*\(", text):
            continue
        if not _isMapped(base, sigs[name]):
            continue  # this exact overload isn't mapped (e.g. a same-base local helper)
        target = mangle(base, sigs[name], overloaded)
        if not target:  # None -> adapted signature, keep hand-written
            unsupported.append(name + "(" + ", ".join(sigs[name]) + ")")
            continue
        text = re.sub(r"\b" + re.escape(name) + r"\s*\(", target + "(", text)
    return text, unsupported


def topLevelFns(wgsl):
    '''Yield (name, text) for each top-level `fn` in a WGSL module.'''
    for m in re.finditer(r"\bfn\s+([A-Za-z_]\w*)\s*\(", wgsl):
        brace = wgsl.index("{", m.start())
        yield m.group(1), wgsl[m.start():_matchBrace(wgsl, brace)]


# -----------------------------------------------------------------------------
# lib driver
# -----------------------------------------------------------------------------
#
# transpileLibs() walks genglsl/lib/*.glsl in include order and writes genwgsl/lib/*.wgsl.
# Strategy mirrors nodes (wrap -> naga -> cleanup) but emits full helper libraries:
#   - default: one naga invocation per function, with #included deps inlined as bodies
#   - LIB_USE_SIBLING_BODIES: transitive in-file callee bodies (overload-aware topo sort)
#   - mx_closure_type: static struct preamble + transpiled makeClosureData only

def libNeedsSamplers(src):
    '''True if this lib references samplers or $-token texture uniforms (needs TEXTURE_STUB_PREAMBLE).'''
    return bool(re.search(r"\btexture\w*\s*\(|\$texSampler|\$albedoTable|\$envRadiance|\$envIrradiance",
                          src))


def _extractMxCalls(fnBody, knownNames):
    '''Return mx_* callees invoked in fnBody (body only, not the signature).'''
    if "{" not in fnBody:
        return set()
    body = fnBody[fnBody.index("{") + 1:fnBody.rfind("}")]
    return {m.group(1) for m in re.finditer(r"\b(mx_\w+)\s*\(", body) if m.group(1) in knownNames}


def sortFunctionsTopo(fns):
    '''Reorder function definitions so callees precede callers (naga requirement).

    Overload-aware: each (name, param-types) pair is a distinct node so naga receives every
    callee body, not just the first overload sharing a name.'''
    if len(fns) <= 1:
        return fns

    byName = {}
    keyToFn = {}
    for fn in fns:
        k = fnSigKey(fn)
        byName.setdefault(fn["name"], []).append(fn)
        keyToFn[k] = fn

    localNames = set(byName.keys())
    deps = {}
    for fn in fns:
        k = fnSigKey(fn)
        depKeys = []
        for callee in _extractMxCalls(fn["full"], localNames):
            for calleeFn in byName.get(callee, []):
                ck = fnSigKey(calleeFn)
                if ck in keyToFn:
                    depKeys.append(ck)
        deps[k] = depKeys

    orderKeys, temp, perm = [], set(), set()

    def visit(k):
        if k in perm:
            return
        if k in temp:
            return
        temp.add(k)
        for dk in deps.get(k, ()):
            visit(dk)
        temp.remove(k)
        perm.add(k)
        orderKeys.append(k)

    for fn in fns:
        visit(fnSigKey(fn))

    return [keyToFn[k] for k in orderKeys]


def rebuildFnBody(fns):
    '''Concatenate function definitions in topo order for a single naga translation unit.'''
    return "\n\n".join(fn["full"] for fn in fns)


def expandLibIncludes(text, gllibDir, seen=None):
    '''Inline `#include \"lib/...\"` bodies so naga sees full dependency definitions.

    Recursive with `seen` to break include cycles. Only `lib/` includes are expanded (not
    cross-library paths). Used for per-function dep context and whole-file transpile.'''
    seen = seen or set()

    def replacer(match):
        incPath = match.group(1)
        if not incPath.startswith("lib/"):
            return match.group(0)
        stem = Path(incPath).stem
        if stem in seen:
            return ""
        seen.add(stem)
        incFile = gllibDir / (stem + ".glsl")
        if not incFile.is_file():
            return ""
        incText = expandLibTokens(incFile.read_text(encoding="utf-8"))
        incText = expandLibIncludes(incText, gllibDir, seen)
        incText = stripIncludes(incText)
        return incText + "\n"

    return re.sub(r'#include\s+"([^"]+)"\s*\n', replacer, text)


def _mxCallsInText(text):
    '''Return mx_* names invoked in text (function bodies and preamble, not signatures).'''
    calls = set()
    fns = parseFunctions(text)
    if fns:
        preamble = text[:text.index(fns[0]["full"])]
        calls |= {m.group(1) for m in re.finditer(r"\b(mx_\w+)\s*\(", preamble)}
        for fn in fns:
            body = fn["full"][fn["full"].index("{") + 1:fn["full"].rfind("}")]
            calls |= {m.group(1) for m in re.finditer(r"\b(mx_\w+)\s*\(", body)}
    else:
        calls |= {m.group(1) for m in re.finditer(r"\b(mx_\w+)\s*\(", text)}
    return calls


def protoBlockForBody(bodySrc, protos, definedSigs):
    '''Emit only prototypes for mx_* helpers referenced in bodySrc and not already defined.'''
    called = _mxCallsInText(bodySrc)
    lines = []
    for (nm, t), p in sorted(protos.items()):
        if (nm, t) in definedSigs:
            continue
        if nm in called:
            lines.append(p)
    return "\n".join(lines)


def siblingCalleeClosure(targetFn, localFns):
    '''Local functions transitively called by targetFn (all overloads of each called name).'''
    byName = {}
    for fn in localFns:
        byName.setdefault(fn["name"], []).append(fn)
    localNames = set(byName.keys())

    needed = set()
    stack = [targetFn]
    while stack:
        fn = stack.pop()
        key = fnSigKey(fn)
        if key in needed:
            continue
        needed.add(key)
        for callee in _extractMxCalls(fn["full"], localNames):
            for calleeFn in byName.get(callee, []):
                if fnSigKey(calleeFn) not in needed:
                    stack.append(calleeFn)

    closure = [fn for fn in localFns if fnSigKey(fn) in needed]
    return sortFunctionsTopo(closure)


def filePreambleBeforeFns(src):
    '''Struct/const text before the first function definition in a lib fragment.'''
    stripped = stripIncludes(src)
    fns = parseFunctions(stripped)
    if not fns:
        return ""
    return stripped[:stripped.index(fns[0]["full"])]


def applyLibWgslPatches(stem, text):
    '''Stem-specific fixes for transpiled lib output (generator/runtime conventions).'''
    if stem == "mx_microfacet_specular":
        # Generator emits split env texture + sampler; match hand-port latlong signature.
        text = re.sub(
            r"fn mx_latlong_map_lookup\([^)]+\)[^{]*\{[^}]*\}",
            """fn mx_latlong_map_lookup(dir: vec3f, transform: mat4x4f, lod: f32, envTex: texture_2d<f32>, envSampler: sampler) -> vec3f {
    let envDir = normalize((transform * vec4f(dir, 0.0)).xyz);
    let uv = mx_latlong_projection(envDir);
    return textureSampleLevel(envTex, envSampler, uv, lod).rgb;
}""",
            text,
            count=1,
            flags=re.S,
        )
    return text


def transpileLibFileSiblings(glslPath, outPath, base, protos, overloaded, libName, src, raw,
                                header, samplerPreamble, gllibDir):
    '''Per-function transpile with transitive in-file callee bodies (naga ordering fix).'''
    stem = glslPath.stem
    stripped = stripIncludes(src)
    localFns = parseFunctions(stripped)
    if not localFns:
        return False

    filePreamble = filePreambleBeforeFns(src)
    incLines = "\n".join(
        f'#include "{i}"\n' for i in re.findall(r'#include\s+"([^"]+)"', raw) if i.startswith("lib/"))
    depSrc = expandLibIncludes(incLines, gllibDir) if incLines else ""
    depSrc = stripIncludes(depSrc)
    for f in localFns:
        depSrc = depSrc.replace(f["full"], "")

    depFns = parseFunctions(depSrc) if depSrc else []
    depPreamble = ""
    if depFns:
        depPreamble = depSrc[:depSrc.index(depFns[0]["full"])]
    depNames = {fn["name"] for fn in depFns}

    outputs = []
    for targetFn in localFns:
        types = fnParamTypes(targetFn["params"])
        outName = wgslFnName(targetFn["name"], types, overloaded)
        siblings = siblingCalleeClosure(targetFn, localFns)

        # Pull in dep-file helpers transitively called from the sibling closure.
        neededDep = []
        neededDepKeys = set()
        stack = list(siblings)
        while stack:
            fn = stack.pop()
            for callee in _extractMxCalls(fn["full"], depNames):
                for depFn in depFns:
                    if depFn["name"] == callee:
                        k = fnSigKey(depFn)
                        if k not in neededDepKeys:
                            neededDepKeys.add(k)
                            neededDep.append(depFn)
                            stack.append(depFn)

        allBodyFns = sortFunctionsTopo(neededDep + siblings)
        callees = [fn for fn in allBodyFns if fnSigKey(fn) != fnSigKey(targetFn)]
        callees = sortFunctionsTopo(callees)
        ordered = callees + [targetFn]
        siblingBody = rebuildFnBody(ordered)
        siblingSigs = {fnSigKey(fn) for fn in ordered}
        definedSigs = siblingSigs
        combined = filePreamble + depPreamble + siblingBody
        protoBlock = protoBlockForBody(combined, protos, definedSigs)
        glsl = ("#version 450\n" + LIB_PREAMBLE + samplerPreamble + base + "\n" +
                filePreamble + depPreamble + "\n" + protoBlock + "\n" + siblingBody +
                FRAG_MAIN_EPILOGUE)
        wgsl, err = nagaTranspileGlsl(
            glsl, outPath.parent / f"_debug_lib_{stem}_{targetFn['name']}.frag"
            if os.environ.get("MTLX_DEBUG") else None)
        if wgsl is None:
            print(f"  FAIL lib/{glslPath.name}::{targetFn['name']}: {err}")
            return False
        text = extractTranspiledFn(wgsl, targetFn["name"], outName, glslTypes=types)
        if text is None:
            print(f"  FAIL lib/{glslPath.name}::{targetFn['name']}: not found in naga output")
            return False
        # Overloaded calls: resolve by naga's actual per-module signatures (its stub numbering here
        # is topological, not the sorted order remapCalls assumes), then run the shared cleanup.
        text, unsupported = remapCallsByNagaSig(text, wgsl, targetFn["name"], overloaded)
        if unsupported:
            print(f"  FAIL lib/{glslPath.name}::{targetFn['name']}: unmapped call(s) {unsupported}")
            return False
        text, _ = postprocessWgslFn(text, targetFn["name"], protos, overloaded, remap=False,
                                      glslParamNames=fnParamNames(targetFn["params"]))
        outputs.append(targetFn.get("lead", "") + injectInlineComments(targetFn["full"], text))

    structs = transpileGlslStructs(stripped)
    consts = transpileGlslConsts(stripped)
    preamble = ("\n\n".join(structs + consts) + "\n\n") if structs or consts else ""
    srcRel = f"libraries/{libName}/genglsl/lib/{glslPath.name}"
    banner = generatedBanner(srcRel)
    allConsts = glslConstNames(base) + constNamesFromWgsl(consts)
    body = resolveConstRefs("\n\n".join(outputs), allConsts)
    body = applyLibWgslPatches(stem, body)
    fileLead = fileLeadComment(raw)
    writeGenerated(outPath, banner + fileLead + header + preamble + body + "\n",
                    f"lib/{glslPath.name}")
    return True


def transpileLibFile(glslPath, outPath, base, protos, overloaded, libName, libroot):
    '''Transpile one genglsl/lib/*.glsl file to genwgsl/lib/*.wgsl.

    Dispatches to _transpileClosureTypeLib, transpileLibFileSiblings, or per-function
    transpile (default). Output: generated banner + #include lines + structs/consts + fn bodies.'''
    raw = glslPath.read_text(encoding="utf-8")
    src = expandLibTokens(raw)
    stem = glslPath.stem
    samplerPreamble = TEXTURE_STUB_PREAMBLE if libNeedsSamplers(raw) else ""

    if stem == "mx_closure_type":
        return _transpileClosureTypeLib(glslPath, outPath, base, protos, overloaded, libName,
                                           libroot)

    includes = [f'#include "{inc.replace(".glsl", ".wgsl")}"'
                for inc in re.findall(r'#include\s+"([^"]+)"', raw)]
    header = ("\n".join(includes) + "\n\n") if includes else ""
    gllibDir = glslPath.parent

    if stem in LIB_USE_SIBLING_BODIES:
        return transpileLibFileSiblings(glslPath, outPath, base, protos, overloaded, libName,
                                           src, raw, header, samplerPreamble, gllibDir)

    stripped = stripIncludes(src)
    localFns = parseFunctions(stripped)
    if not localFns:
        print(f"  SKIP lib/{glslPath.name}: no functions found")
        return False

    incLines = "\n".join(
        f'#include "{i}"\n' for i in re.findall(r'#include\s+"([^"]+)"', raw) if i.startswith("lib/"))
    depSrc = expandLibIncludes(incLines, gllibDir) if incLines else ""
    depSrc = stripIncludes(depSrc)
    # Remove local function bodies from depSrc — only the target fn body is transpiled per pass.
    for f in localFns:
        depSrc = depSrc.replace(f["full"], "")

    outputs = []
    for fn in localFns:
        types = fnParamTypes(fn["params"])
        outName = wgslFnName(fn["name"], types, overloaded)
        protoBlock = "\n".join(
            p for (nm, t), p in sorted(protos.items())
            if not (nm == fn["name"] and t == types))
        glsl = ("#version 450\n" + LIB_PREAMBLE + samplerPreamble + base + "\n" +
                depSrc + "\n" + protoBlock + "\n" + fn["full"] +
                FRAG_MAIN_EPILOGUE)
        wgsl, err = nagaTranspileGlsl(
            glsl, outPath.parent / f"_debug_lib_{stem}_{fn['name']}.frag"
            if os.environ.get("MTLX_DEBUG") else None)
        if wgsl is None:
            print(f"  FAIL lib/{glslPath.name}::{fn['name']}: {err}")
            return False
        text = extractTranspiledFn(wgsl, fn["name"], outName)
        if text is None:
            print(f"  FAIL lib/{glslPath.name}::{fn['name']}: not found in naga output")
            return False
        text, unsupported = postprocessWgslFn(text, fn["name"], protos, overloaded, remap=True,
                                                  glslParamNames=fnParamNames(fn["params"]))
        if unsupported:
            print(f"  FAIL lib/{glslPath.name}::{fn['name']}: unmapped call(s) {unsupported}")
            return False
        outputs.append(fn.get("lead", "") + injectInlineComments(fn["full"], text))

    structs = transpileGlslStructs(stripped)
    consts = transpileGlslConsts(stripped)
    preambleParts = structs + consts
    preamble = ("\n\n".join(preambleParts) + "\n\n") if preambleParts else ""

    srcRel = f"libraries/{libName}/genglsl/lib/{glslPath.name}"
    banner = generatedBanner(srcRel)
    allConsts = glslConstNames(base) + constNamesFromWgsl(consts)
    body = resolveConstRefs("\n\n".join(outputs), allConsts)
    fileLead = fileLeadComment(raw)
    writeGenerated(outPath, banner + fileLead + header + preamble + body + "\n",
                    f"lib/{glslPath.name}")
    return True


def _transpileClosureTypeLib(glslPath, outPath, base, protos, overloaded, libName, libroot):
    '''Special handler for mx_closure_type: prepend shared structs, transpile makeClosureData.

    GLSL only defines ClosureData + constructor macro; genwgsl nodes expect BSDF/VDF/FresnelData
    types from this file. The struct block is wgslClosurePreamble(libroot) -- derived from
    mx_closure_type.glsl, mx_microfacet_specular.glsl, and GlslSyntax.cpp -- not a hand-written
    preamble. Function bodies still come from naga.'''
    raw = glslPath.read_text(encoding="utf-8")
    src = expandLibTokens(raw)
    outputs = []
    for fn in parseFunctions(src):
        types = fnParamTypes(fn["params"])
        outName = wgslFnName(fn["name"], types, overloaded)
        protoBlock = "\n".join(
            p for (nm, t), p in sorted(protos.items())
            if not (nm == fn["name"] and t == types))
        glsl = ("#version 450\n" + LIB_PREAMBLE + base + "\n" + protoBlock +
                "\n" + fn["full"] + FRAG_MAIN_EPILOGUE)
        wgsl, err = nagaTranspileGlsl(glsl)
        if wgsl is None:
            print(f"  FAIL lib/{glslPath.name}::{fn['name']}: {err}")
            return False
        text = extractTranspiledFn(wgsl, fn["name"], outName)
        if text is None:
            print(f"  FAIL lib/{glslPath.name}::{fn['name']}: not found in naga output")
            return False
        text, unsupported = postprocessWgslFn(text, fn["name"], protos, overloaded, remap=False,
                                                  glslParamNames=fnParamNames(fn["params"]))
        if unsupported:
            print(f"  FAIL lib/{glslPath.name}::{fn['name']}: {unsupported}")
            return False
        outputs.append(fn.get("lead", "") + injectInlineComments(fn["full"], applyFieldRenames(text)))

    srcRel = f"libraries/{libName}/genglsl/lib/{glslPath.name}"
    banner = generatedBanner(srcRel)
    fileLead = fileLeadComment(raw)
    writeGenerated(outPath,
                    banner + fileLead + wgslClosurePreamble(libroot).strip() + "\n\n"
                    + "\n\n".join(outputs) + "\n",
                    f"lib/{glslPath.name}")
    return True


def transpileLibs(libroot, outroot, libs, base, protos, only=None):
    '''Transpile all genglsl/lib/*.glsl helpers to genwgsl/lib/*.wgsl.

    Runs before node transpilation in main(). Returns a list of stems that failed.
    Uses buildContext(nodes=False) for lib-only prototypes.'''
    ok = failed = 0
    unexpected = []
    # Lib-only context: no node protos (inout) and no duplicate closure preamble.
    libBase, libProtos, libOverloaded = buildContext(libroot, libs, nodes=False)
    print("\nTranspiling genglsl/lib/ helpers...")
    for lib in libs:
        gllib = libroot / lib / "genglsl" / "lib"
        if not gllib.is_dir():
            continue
        libFiles = topoSortLibFiles(sorted(gllib.glob("*.glsl")))
        for glsl in libFiles:
            if isHandWrittenLib(lib, glsl.stem):
                print(f"  KEEP lib/{glsl.name} (hand-written; in skip_transpile.txt)")
                continue
            if only and glsl.stem not in only:
                continue
            out = outroot / lib / "genwgsl" / "lib" / (glsl.stem + ".wgsl")
            if transpileLibFile(glsl, out, libBase, libProtos, libOverloaded, lib, libroot):
                ok += 1
            else:
                failed += 1
                unexpected.append(glsl.stem)
    print(f"Lib done: {ok} transpiled, {failed} failures.")
    return unexpected


# -----------------------------------------------------------------------------
# node driver
# -----------------------------------------------------------------------------

def transpile(nodePath, outPath, base, protos, overloaded, libSymbols):
    nodeSrc = nodePath.read_text(encoding="utf-8")
    nodeFns = parseFunctions(nodeSrc)
    if not nodeFns:
        print(f"  SKIP {nodePath.name}: no functions found")
        return False

    outputs = []
    for fn in nodeFns:
        # Supply every known prototype except the function being defined here (siblings and
        # cross-node helpers are all in `protos`, keyed by name+types).
        # Emit sorted by (name, types) so each overloaded base's prototypes are declared in the
        # same order remapCalls indexes them (naga numbers overload stubs by declaration order).
        protoBlock = "\n".join(p for (nm, _t), p in sorted(protos.items()) if nm != fn["name"])
        body = fn["full"]

        # MaterialX `$`-tokens (e.g. $blur, $albedoTable) aren't valid GLSL identifiers, so naga
        # can't parse them. Swap each `$tok` for a legal placeholder `MTLXTOK_tok` before transpiling
        # and restore it afterwards; tokenMap records the reverse mapping for this function.
        tokenMap = {}

        def sentinel(m):
            s = "MTLXTOK_" + m.group(1)
            tokenMap[s] = m.group(0)
            return s
        body = re.sub(r"\$([A-Za-z_]\w*)", sentinel, body)

        # Assemble a complete, naga-parseable fragment shader: version + shared context (structs,
        # #defines, prototypes) + this one real function body + a do-nothing entry point. naga's GLSL
        # frontend requires a staged shader with a main(); it keeps non-entry functions in the output,
        # which is exactly the one body we want back.
        glsl = "#version 450\n" + base + "\n" + protoBlock + "\n" + body + FRAG_MAIN_EPILOGUE

        wgsl, err = nagaTranspileGlsl(
            glsl, outPath.parent / f"_debug_{fn['name']}.frag" if os.environ.get("MTLX_DEBUG") else None)
        if wgsl is None:
            print(f"  FAIL {nodePath.name}::{fn['name']}: {err}")
            return False

        # Pull our one real function out of naga's module (context prototypes become empty stubs) and
        # rename it back to the clean source name -- the same helper the lib path uses.
        text = extractTranspiledFn(wgsl, fn["name"], fn["name"])
        if text is None:
            print(f"  FAIL {nodePath.name}::{fn['name']}: not found in naga output")
            return False

        # Shared post-processing: cleanup, type/float-literal normalization, denaga reconciliation,
        # overload remap, and lib-arity check. Anything the tables mark unsupported (adapted
        # signatures, e.g. the FresnelData BSDF helpers) fails the node so it falls back to the
        # hand-written .wgsl -- yielding a reduced (generated + hand-written) lib.
        text, unsupported = postprocessWgslFn(text, fn["name"], protos, overloaded,
                                                libSymbols=libSymbols, remap=True,
                                                glslParamNames=fnParamNames(fn["params"]))
        if unsupported:
            print(f"  FAIL {nodePath.name}::{fn['name']}: calls adapted/unmapped helper(s) "
                  f"{unsupported} (kept hand-written)")
            return False

        # Restore MaterialX $-tokens last; sentinels are untouched by remap/arity (which match mx_*).
        for s, tok in tokenMap.items():
            text = text.replace(s, tok)

        outputs.append(fn.get("lead", "") + injectInlineComments(fn["full"], text))

    # Re-emit the node's own #include lines with the .glsl->.wgsl extension swap, so the generated
    # fragment pulls in the same lib helpers (now their WGSL versions) the GLSL source did. A node
    # file may define several functions (e.g. a vector2 + float variant); join them in source order.
    includes = [f'#include "{inc.replace(".glsl", ".wgsl")}"'
                for inc in re.findall(r'#include\s+"([^"]+)"', nodeSrc)]
    header = ("\n".join(includes) + "\n\n") if includes else ""

    # Banner marking the file as generated, so it is visually distinct from the hand-written
    # genwgsl nodes it sits next to. Names the genglsl source (lib-relative, so the line is stable
    # regardless of where --libraries points) and the tool. No timestamp: re-running must produce
    # byte-identical output so `git diff` cleanly surfaces drift.
    srcRel = f"libraries/{nodePath.parent.parent.name}/genglsl/{nodePath.name}"
    banner = generatedBanner(srcRel)

    fileLead = fileLeadComment(nodeSrc)
    writeGenerated(outPath, banner + fileLead + header + "\n\n".join(outputs) + "\n",
                    nodePath.name)
    return True


def cleanGenerated(libroot):
    '''Delete every generated genwgsl *.wgsl under --libraries, keeping only the hand-written files
    listed in skip_transpile.txt. Restores a hand-written-only library after an in-place
    (`--out libraries`) generation run. Needs no naga.'''
    libroot = Path(libroot)
    keep = loadDoNotTranspile()
    removed = kept = 0
    print(f"Cleaning generated genwgsl .wgsl under {libroot} ...")
    for wgsl in sorted(libroot.glob("*/genwgsl/**/*.wgsl")):
        if wgsl.relative_to(libroot).as_posix() in keep:
            kept += 1
            continue
        print(f"  RM {wgsl.relative_to(libroot).as_posix()}")
        wgsl.unlink()
        removed += 1
    print(f"Clean done: {removed} generated file(s) removed, {kept} hand-written kept.")
    return removed


def main():
    ap = argparse.ArgumentParser(description="Transpile genglsl node fragments to genwgsl.")
    ap.add_argument("--libraries", default="libraries")
    ap.add_argument("--out", default="build/genwgsl_generated")
    ap.add_argument("--only", nargs="*")
    ap.add_argument("--clean", action="store_true",
                    help="Delete generated genwgsl .wgsl under --libraries (keeping the hand-written "
                         "files in skip_transpile.txt), then exit. Does not run naga.")
    ap.add_argument("--naga", help="Path to the naga CLI (overrides the NAGA env var / PATH lookup).")
    args = ap.parse_args()

    if args.clean:
        cleanGenerated(args.libraries)
        return 0

    # Resolve and preflight naga so a missing tool fails once, with guidance, instead of per node.
    global NAGA
    NAGA = resolveNaga(args.naga)
    version = nagaVersion(NAGA)
    if not version:
        print(f"ERROR: naga CLI not found or not runnable (tried '{NAGA}').\n"
              "       Install it with `cargo install naga-cli`, or pass --naga <path> / set the\n"
              "       NAGA environment variable. See https://github.com/gfx-rs/wgpu/tree/trunk/naga.",
              file=sys.stderr)
        return 2
    print(f"Using naga: {NAGA} ({version})")

    libroot, outroot = Path(args.libraries), Path(args.out)
    # Preamble/token helpers resolve repo paths relative to libroot; must run before transpilation.
    setActiveLibroot(libroot)
    libs = discoverLibs(libroot)
    base, protos, overloaded = buildContext(libroot, libs)

    # Scan-driven preflight: unresolved overloads or unhandled $-tokens are hard errors (they would
    # mis-emit a name or fail naga later, with a more obscure message).
    validationFailed = False
    uncovered = validateOverloadCoverage(protos, overloaded)
    if uncovered:
        validationFailed = True
        print("ERROR: overloaded helpers with no mangle() mapping (add a SUFFIX_SCHEME/EXCEPTIONS "
              "entry): " + ", ".join(f"{n}{t}" for n, t in uncovered))
    unhandledTokens = validateTokenCoverage(libroot, libs)
    if unhandledTokens:
        validationFailed = True
        print("ERROR: $-tokens in transpiled lib sources not covered by HwConstants/NAGA_LIB_STUBS: "
              + ", ".join(f"{tok} ({src})" for tok, src in sorted(unhandledTokens.items())))

    # Lib helpers first: nodes #include genwgsl/lib/*.wgsl and checkLibArity reads fresh output.
    libUnexpected = transpileLibs(libroot, outroot, libs, base, protos, only=args.only)
    libSymbols = buildWgslLibSymbols(libroot, libs, outroot=outroot)

    # Validate mangle() names against the actual genwgsl lib (hand-written stdlib from libroot,
    # generated helpers from outroot). Skipped for a partial --only run, which won't regenerate
    # every referenced helper.
    if not args.only:
        valSymbols = dict(buildWgslLibSymbols(libroot, libs))
        valSymbols.update(libSymbols)
        missingNames = validateLibNames(protos, valSymbols)
        if missingNames:
            validationFailed = True
            print("ERROR: mangle() produced names absent from the genwgsl lib: "
                  + ", ".join(missingNames))

    ok = skip = 0
    nodeExpected, nodeUnexpected = [], []
    print("\nTranspiling genglsl node fragments...")
    for lib in libs:
        gldir = libroot / lib / "genglsl"
        if not gldir.is_dir():
            continue
        for glsl in sorted(gldir.glob("mx_*.glsl")):
            baseName = glsl.stem
            if args.only and baseName not in args.only:
                continue
            if any(p.search(baseName) for p in SKIP_PATTERNS):
                print(f"  SKIP {glsl.name}: texture/sampler node (unsupported by naga)")
                skip += 1
                continue
            out = outroot / lib / "genwgsl" / (baseName + ".wgsl")
            if transpile(glsl, out, base, protos, overloaded, libSymbols):
                ok += 1
                if baseName in EXPECTED_FALLBACK:
                    # A node we expected to stay hand-written now transpiles cleanly -- the lib
                    # divergence it depended on was probably resolved. Not fatal, but worth flagging.
                    print(f"  WARN {glsl.name}: now transpiles cleanly; remove it from "
                          f"EXPECTED_FALLBACK and commit the generated version.")
            elif baseName in EXPECTED_FALLBACK:
                nodeExpected.append(baseName)
            else:
                nodeUnexpected.append(baseName)

    print(f"\nDone: {ok} nodes transpiled, {skip} skipped, "
          f"{len(nodeExpected)} expected fallbacks, {len(nodeUnexpected)} unexpected failures.")
    allUnexpected = libUnexpected + nodeUnexpected
    if allUnexpected:
        print("ERROR: files that should transpile failed: " + ", ".join(sorted(set(allUnexpected))))
        return 1
    if validationFailed:
        print("ERROR: scan-driven validation failed (see messages above).")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
