#include "adsk/impl/shadergen/osl/source/adskNoiseFunctions.osl"

void adskCellNoise2d_color3(vector position, float amplitude, float frequency, vector distortion, float distortionRatio, output color result)
{
	position *= 8;
	position[0] += distortion[0] * distortionRatio;
	position[1] += (distortion[1] + 0.2) * distortionRatio;

	float noise = simplex_cellular2d(position * frequency);

	result = color(amplitude * noise);
}
