void mx_remap_vector2(vector2 in, vector2 inlow, vector2 inhigh, float gamma, vector2 outlow, vector2 outhigh, int doclamp, output vector2 result)
{
    // remap from [inlow, inhigh] to [0,1]
    result = remap(in, inlow, inhigh, 0, 1, 0);

    // apply gamma
    result = fgamma(result, gamma);

    // remap from [0,1] to [outlow, outhigh]
    result = remap(result, 0, 1, outlow, outhigh, doclamp); 
}
