void mx_remap_vector4(vector4 in, vector4 inlow, vector4 inhigh, float gamma, vector4 outlow, vector4 outhigh, int doclamp, output vector4 result)
{
    // remap from [inlow, inhigh] to [0,1]
    result = remap(in, inlow, inhigh, 0, 1, 0);

    // apply gamma
    result = fgamma(result, gamma);

    // remap from [0,1] to [outlow, outhigh]
    result = remap(result, 0, 1, outlow, outhigh, doclamp); 
}
