#include "Source/ShaderGen/OSL/adskNoiseFunctions.osl"

void adskCellNoise2d_color3(vec2 position, float amplitude, float frequency, vec2 distortion, float distortionRatio, out color result)
{
	position *= 8;
	position.x += distortion.x * distortionRatio;
	position.y += (distortion.y + 0.2) * distortionRatio;

	float noise = simplex_cellular2d(position * frequency);

	result = color(amplitude * noise);
}
