void mx_image_float(string file, string layer, float default_value, vector texcoord, string uaddressmode, string vaddressmode, string framerange, int frameoffset, string frameendaction, output float out)
{
    vdirection(texcoord, texcoord);
    color missingColor = default_value;
    color rgb = texture(file, texcoord[0], texcoord[1], "subimage", layer, "missingcolor", missingColor, "wrap", uaddressmode);
    out = rgb[0];
}
