void mx_mix_surfaceshader(surfaceshader fg, surfaceshader bg, float w, output surfaceshader result)
{
    result.opacity = mix(bg.opacity, fg.opacity, w);
    // Condition the represented surface response on the interaction not being cut out.
    float conditional_mix = result.opacity > 0.0 ? w * fg.opacity / result.opacity : 0.0;
    result.bsdf = mix(bg.bsdf, fg.bsdf, conditional_mix);
    result.edf = mix(bg.edf, fg.edf, conditional_mix);
}
