name: build_windows

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build_windows:

    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Windows_VS2017_Win32_Python27
          os: windows-2016
          architecture: x86
          python: 2.7
          cmake_config: -G "Visual Studio 15 2017" -A "Win32"

        - name: Windows_VS2017_x64_Python37
          os: windows-2016
          architecture: x64
          python: 3.7
          cmake_config: -G "Visual Studio 15 2017" -A "x64"

        - name: Windows_VS2019_x64_Python38
          os: windows-2019
          architecture: x64
          python: 3.8
          cmake_config: -G "Visual Studio 16 2019" -A "x64"

    runs-on: ${{matrix.os}}

    env:
      config: Release

    steps:
    - name: Sync Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: Create Build Directory
      run: mkdir build
      
    - name: CMake Generate
      run: cmake -DMATERIALX_BUILD_PYTHON=ON -DMATERIALX_BUILD_VIEWER=ON -DMATERIALX_TEST_RENDER=OFF -DMATERIALX_WARNINGS_AS_ERRORS=ON ${{matrix.cmake_config}} ..
      working-directory: build

    - name: CMake Build
      run: cmake --build . --target install --config ${{env.config}}
      working-directory: build

    - name: Upload Installed Package
      uses: actions/upload-artifact@v2
      with:
        name: MaterialX_${{matrix.name}}
        path: build/installed/

    - name: CMake Unit Tests
      run: ctest -VV --output-on-failure --build-config ${{env.config}}
      working-directory: build

    - name: Generate Test HTML
      if: ${{matrix.generate_html == 'ON'}}
      run: cmake -E chdir ../python/MaterialXTest python tests_to_html.py
      working-directory: build

    - name: Upload Test HTML
      uses: actions/upload-artifact@v2
      if: ${{matrix.generate_html == 'ON'}}
      with:
        name: MaterialX_${{matrix.name}}_test_html
        path: build/source/MaterialXTest/tests.html

    - name: Upload Test Images
      uses: actions/upload-artifact@v2
      if: ${{matrix.generate_html == 'ON'}}
      with:
        name: MaterialX_${{matrix.name}}_test_images
        path: build/source/MaterialXTest/**/*.png

    - name: Python Tests
      run: |
        cmake -E chdir ../python/MaterialXTest python main.py
        cmake -E chdir ../python/MaterialXTest python genshader.py
      working-directory: build
